<?php

// Tampilkan header
require_once __DIR__ . '/../../includes/header.php';

// Call modal post
require_once __DIR__ . '/../../models/Post.php';

// Ambil semua post
$posts = getAllPosts();

// Sample data for stories and suggestions
$stories = [
    [
        'username' => '_dwiirhma', 
        'is_current_user' => true,
        'avatar' => '../../public/img/gambar1.jpg',
        'stories' => [
            ['image' => '../../public/img/gambar3.jpg', 'timestamp' => '2 jam'],
            ['image' => '../../public/img/gambar4.jpg', 'timestamp' => '4 jam']
        ],
        'has_story' => true
    ],
    [
        'username' => '_8lololowme', 
        'avatar' => '../../public/img/jamet.jpg',
        'stories' => [
            ['image' => '../../public/img/gambar4.jpg', 'timestamp' => '1 jam'],
            ['image' => '../../public/img/gambar5.jpg', 'timestamp' => '3 jam'],
            ['image' => '../../public/img/gambar6.jpg', 'timestamp' => '5 jam']
        ],
        'has_story' => true
    ],
    [
        'username' => 'dumphileee', 
        'avatar' => '../../public/img/dumphileee.jpg',
        'stories' => [
            ['image' => '../../public/img/gambar6.jpg', 'timestamp' => '30 menit']
        ],
        'has_story' => true
    ],
    [
        'username' => 'arinassjj', 
        'avatar' => '../../public/img/arin.jpg',
        'stories' => [
            ['image' => '../../public/img/gambar5.jpg', 'timestamp' => '6 jam']
        ],
        'has_story' => true
    ],
    [
        'username' => 'wijaayakusuma', 
        'avatar' => '../../public/img/jaya.jpg',
        'stories' => [
            ['image' => '../../public/img/gambar7.jpg', 'timestamp' => '8 jam'],
            ['image' => '../../public/img/gambar8.jpg', 'timestamp' => '10 jam']
        ],
        'has_story' => true
    ],
    [
        'username' => 'my2ndpagee_', 
        'avatar' => '../../public/img/nina.jpg',
        'stories' => [
            ['image' => '../../public/img/gambar9.jpg', 'timestamp' => '12 jam']
        ],
        'has_story' => true
    ]
];

$suggestions = [
    ['username' => 'houseoffchilll', 'avatar' => '../../public/img/houseofchill.jpg','mutual' => 'Disarankan untuk Anda'],
    ['username' => 'aliviaa_putrii', 'avatar' => '../../public/img/lipia.jpg', 'mutual' => 'Disarankan untuk Anda'],
    ['username' => 'odyssmt_', 'avatar' => '../../public/img/ody.jpg', 'mutual' => 'Disarankan untuk Anda'],
    ['username' => 'oktaviatamd_', 'avatar' => '../../public/img/manda.jpg', 'mutual' => 'Diikuti oleh mamanx_x'],
    ['username' => 'whysetia_', 'avatar' => '../../public/img/wahyu.jpg', 'mutual' => 'Diikuti oleh fajridn_']
];

function renderHighlightsSection($stories) {
    ?>
    <div class="highlights-section">
        <div class="highlights-container">
            <?php foreach ($stories as $index => $story): ?>
                <div class="highlight-item" data-story-index="<?= $index ?>">
                    <?php if (isset($story['is_current_user']) && $story['is_current_user']): ?>
                        <!-- Add Story Button for Current User -->
                        <div class="story-ring add-story" onclick="openAddStory()">
                            <img src="<?= htmlspecialchars($story['avatar']) ?>" alt="<?= htmlspecialchars($story['username']) ?>" class="highlight-avatar">
                            <div class="add-story-plus">+</div>
                        </div>
                        <span class="highlight-username">Story Anda</span>
                    <?php else: ?>
                        <div class="story-ring <?= $story['has_story'] ? 'has-story' : '' ?>" onclick="openStory(<?= $index ?>)">
                            <img src="<?= htmlspecialchars($story['avatar']) ?>" alt="<?= htmlspecialchars($story['username']) ?>" class="highlight-avatar">
                        </div>
                        <span class="highlight-username"><?= htmlspecialchars($story['username']) ?></span>
                    <?php endif; ?>
                </div>
            <?php endforeach; ?>
        </div>
    </div>

    <!-- Story Modal -->
    <div id="storyModal" class="story-modal">
        <div class="story-container">
            <div class="story-header">
                <div class="story-progress-bars">
                    <!-- Progress bars will be generated by JavaScript -->
                </div>
                <div class="story-user-info">
                    <img id="storyUserAvatar" src="" alt="" class="story-user-avatar">
                    <span id="storyUsername"></span>
                    <span id="storyTimestamp" class="story-timestamp"></span>
                </div>
                <button class="story-close" onclick="closeStory()">×</button>
            </div>
            
            <div class="story-content">
                <img id="storyImage" src="" alt="Story">
                <div class="story-navigation">
                    <div class="story-prev" onclick="previousStory()"></div>
                    <div class="story-next" onclick="nextStory()"></div>
                </div>
            </div>
            
            <div class="story-actions">
                <input type="text" placeholder="Kirim pesan" class="story-message-input">
                <button class="story-heart">❤</button>
                <button class="story-share">📤</button>
            </div>
        </div>
    </div>

    <!-- Add Story Modal -->
    <div id="addStoryModal" class="story-modal add-story-modal">
        <div class="add-story-container">
            <div class="add-story-header">
                <h3>Buat story</h3>
                <button class="story-close" onclick="closeAddStory()">×</button>
            </div>
            
            <!-- Photo Upload Area -->
            <div class="photo-upload-area" id="photoUploadArea">
                <div class="upload-placeholder">
                    <div class="upload-icon">📷</div>
                    <h3>Pilih foto untuk story</h3>
                    <p>Klik untuk memilih foto atau drag & drop</p>
                    <input type="file" id="storyPhotoInput" accept="image/*" style="display: none;">
                    <button class="upload-btn" onclick="document.getElementById('storyPhotoInput').click()">
                        Pilih Foto
                    </button>
                </div>
            </div>

            <!-- Story Preview -->
            <div class="story-preview" id="storyPreview" style="display: none;">
                <!-- Story Tools Header -->
                <div class="story-tools-header">
                    <button class="story-tool-btn" onclick="closeAddStory()">✕</button>
                    <button class="story-tool-btn" onclick="toggleBoomerang()">∞</button>
                    <button class="story-tool-btn" onclick="addText()" id="textToolBtn">Aa</button>
                    <button class="story-tool-btn" onclick="addSticker()">😊</button>
                    <button class="story-tool-btn" onclick="addMusic()">♪</button>
                    <button class="story-tool-btn" onclick="addSparkles()">✨</button>
                    <button class="story-tool-btn more-tools" onclick="showMoreTools()">⋯</button>
                </div>
                
                <div class="preview-content">
                    <img id="previewImage" src="" alt="Story Preview">
                    <!-- Draggable text elements will be added here -->
                    <div class="draggable-elements" id="draggableElements"></div>
                </div>
                
                <!-- Bottom Text Input -->
                <div class="story-text-input-bottom" id="storyTextInputBottom" style="display: none;">
                    <input type="text" id="storyTextInput" placeholder="Tambahkan keterangan..." maxlength="100">
                    <div class="text-style-options">
                        <button class="text-style-btn" onclick="changeTextStyle('classic')" data-style="classic">A</button>
                        <button class="text-style-btn" onclick="changeTextStyle('modern')" data-style="modern">𝗔</button>
                        <button class="text-style-btn" onclick="changeTextStyle('neon')" data-style="neon">𝔸</button>
                        <button class="text-style-btn" onclick="changeTextStyle('typewriter')" data-style="typewriter">𝙰</button>
                    </div>
                    <div class="text-color-options">
                        <div class="color-picker">
                            <button class="color-btn" data-color="white" style="background: white; border: 2px solid #333;"></button>
                            <button class="color-btn" data-color="#ff3040" style="background: #ff3040;"></button>
                            <button class="color-btn" data-color="#0095f6" style="background: #0095f6;"></button>
                            <button class="color-btn" data-color="#00d924" style="background: #00d924;"></button>
                            <button class="color-btn" data-color="#ffcc00" style="background: #ffcc00;"></button>
                            <button class="color-btn" data-color="#ff6b35" style="background: #ff6b35;"></button>
                            <button class="color-btn" data-color="#8a2be2" style="background: #8a2be2;"></button>
                            <button class="color-btn" data-color="#ff1493" style="background: #ff1493;"></button>
                        </div>
                    </div>
                    <button class="done-text-btn" onclick="addTextToStory()">Selesai</button>
                </div>
                
                <!-- Bottom Story Actions -->
                <div class="story-bottom-actions">
                    <div class="story-bottom-left">
                        <button class="bottom-action-btn" onclick="saveStoryDraft()">
                            <span class="btn-icon">💾</span>
                        </button>
                        <button class="bottom-action-btn" onclick="toggleStoryPrivacy()" id="privacyBtn">
                            <span class="btn-icon">👁</span>
                        </button>
                    </div>
                    
                    <div class="story-bottom-center">
                        <div class="share-options">
                            <div class="share-option" onclick="shareToStory('story')">
                                <div class="share-avatar">
                                    <img src="../../public/img/gambar3.jpg" alt="Your Story">
                                </div>
                                <span>Cerita Anda</span>
                            </div>
                            <div class="share-option" onclick="shareToStory('close_friends')">
                                <div class="share-avatar close-friends">
                                    <img src="../../public/img/gambar3.jpg" alt="Close Friends">
                                    <div class="close-friends-badge">⭐</div>
                                </div>
                                <span>Teman Dekat</span>
                            </div>
                        </div>
                    </div>
                    
                    <div class="story-bottom-right">
                        <button class="send-story-btn" onclick="showSendStoryModal()">
                            <span class="send-icon">→</span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Story Success Modal -->
    <div id="storySuccessModal" class="story-modal">
        <div class="success-container">
            <div class="success-content">
                <div class="success-icon">✅</div>
                <h3>Story berhasil dibagikan!</h3>
                <p>Story Anda sekarang dapat dilihat oleh pengikut selama 24 jam</p>
                <button class="success-btn" onclick="closeSuccessModal()">OK</button>
            </div>
        </div>
    </div>
    <?php
}

function renderFeedSection($posts, $stories) {
    ?>
    <div class="section" id="feed">
        <div class="feed-section">
            <!-- Feed Posts -->
            <?php if (!empty($posts)): ?>
                <?php foreach ($posts as $post): ?>
                    <div class="feed-post">
                        <!-- Post Header -->
                        <div class="post-header">
                            <img src="<?= htmlspecialchars($post['avatar'] ?? 'public/img/gambar3.jpg') ?>" alt="<?= htmlspecialchars($post['username']) ?>" class="post-avatar">
                            <a href="#" class="post-username"><?= htmlspecialchars($post['username']) ?></a>
                            <span class="post-time"><?= date('j M', strtotime($post['created_at'] ?? 'now')) ?></span>
                            <button class="post-options">⋯</button>
                        </div>
                        
                        <!-- Post Images (multiple) -->
                        <?php if (!empty($post['image'])): ?>
                            <div class="post-images">
                 <img src="<?= '/public/img/' . htmlspecialchars($post['image']) ?>" alt="Post Image">
                                
                            </div>
                        <?php else: ?>
                            <div class="post-placeholder">
                                <i class="fas fa-camera fa-2x"></i>
                            </div>
                        <?php endif; ?>
                        
                        <!-- Post Actions -->
                        <div class="post-actions">
                            <button class="post-action">❤</button>
                            <button class="post-action">💬</button>
                            <button class="post-action">📤</button>
                            <button class="post-action">🔖</button>
                        </div>
                        
                        <!-- Post Likes & Caption -->
                        <div class="post-content-text">
                            <div class="post-likes">42 suka</div>
                            <div class="post-caption">
                                <span class="username"><?= htmlspecialchars($post['username']) ?></span>
                                <?= htmlspecialchars($post['caption'] ?? '') ?>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php else: ?>
                <div class="no-posts">
                    <i class="fas fa-camera fa-3x mb-3"></i>
                    <h3>Belum ada postingan di feed</h3>
                    <p>Mulai berbagi momen Anda atau ikuti akun lain</p>
                </div>
            <?php endif; ?>
        </div>
    </div>
    <?php
}

function renderRightSidebar($suggestions) {
    ?>
    <div class="sidebar-right">
        <div class="profile-switch">
            <div class="profile-info">
                <form id="formProfilePic" enctype="multipart/form-data">
                    <label for="profilePicInput">
                        <img id="profileAvatar" src="../../public/img/gambar1.jpg" alt="_dwiirhma" class="profile-avatar">
                    </label>
                    <input type="file" id="profilePicInput" name="profile_pic" accept="image/*" style="display:none;">
                </form>
                <div class="profile-details">
                    <h4>_dwiirhma</h4>
                </div>
            </div>
            <button class="switch-btn">Alihkan</button>
        </div>

        <div class="suggestions">
            <div class="suggestions-header">
                <h3 class="suggestions-title">Disarankan untuk Anda</h3>
                <a href="#" class="see-all">Lihat Semua</a>
            </div>
            
            <?php foreach($suggestions as $suggestion): ?>
            <div class="suggestion-item">
                <div class="suggestion-info">
                    <img src="<?php echo $suggestion['avatar']; ?>" alt="<?php echo $suggestion['username']; ?>" class="suggestion-avatar">
                    <div class="suggestion-details">
                        <h5><?php echo $suggestion['username']; ?></h5>
                        <p><?php echo $suggestion['mutual']; ?></p>
                    </div>
                </div>
                <button class="follow-btn">Ikuti</button>
            </div>
            <?php endforeach; ?>
        </div>

        <div class="footer">
            <div class="footer-links">
                <a href="#">Tentang</a> • 
                <a href="#">Bantuan</a> • 
                <a href="#">Pers</a> • 
                <a href="#">API</a> • 
                <a href="#">Pekerjaan</a> • 
                <a href="#">Privasi</a> • 
                <a href="#">Ketentuan</a> • 
                <a href="#">Lokasi</a> • 
                <a href="#">Bahasa</a> • 
                <a href="#">Verifikasi Meta</a>
            </div>
            <p>© 2025 INSTAGRAM FROM META</p>
        </div>
    </div>
    <?php
}
?>

    <div class="instagram-container">
        <!-- Main Content -->
        <main class="main-content">
            <?php renderHighlightsSection($stories); ?>
            <?php renderFeedSection($posts, $stories); ?>
        </main>
        
        <?php renderRightSidebar($suggestions); ?>
    </div>

   

    <!-- <script src="modules/home/instagram.js"></script> -->
</div>
     <script>
        // Story data from PHP
        const storiesData = <?= json_encode($stories) ?>;
        let currentUserIndex = 0;
        let currentStoryIndex = 0;
        let storyTimer;
        let progressTimer;
        let currentTextColor = 'white';
        let currentTextSize = 18;
        let currentTextStyle = 'classic';
        let draggedElement = null;
        let textElements = [];
        let storyPrivacy = 'public'; // public or close_friends

        // Story Tools Functions
        function toggleBoomerang() {
            // Toggle boomerang effect (placeholder)
            const btn = event.target;
            btn.classList.toggle('active');
        }

        function addText() {
            const textInput = document.getElementById('storyTextInputBottom');
            const isVisible = textInput.style.display !== 'none';
            
            if (isVisible) {
                textInput.style.display = 'none';
                document.getElementById('textToolBtn').classList.remove('active');
            } else {
                textInput.style.display = 'block';
                document.getElementById('textToolBtn').classList.add('active');
                document.getElementById('storyTextInput').focus();
            }
        }

        function addSticker() {
            // Add sticker functionality (placeholder)
            alert('Fitur sticker akan segera hadir!');
        }

        function addMusic() {
            // Add music functionality (placeholder)
            alert('Fitur musik akan segera hadir!');
        }

        function addSparkles() {
            // Add sparkles effect (placeholder)
            alert('Fitur efek akan segera hadir!');
        }

        function showMoreTools() {
            // Show more tools (placeholder)
            alert('Lebih banyak tools akan segera hadir!');
        }

        function changeTextStyle(style) {
            currentTextStyle = style;
            
            // Update active button
            document.querySelectorAll('.text-style-btn').forEach(btn => {
                btn.classList.remove('active');
            });
            document.querySelector([data-style="${style}"]).classList.add('active');
        }

        function addTextToStory() {
            const textInput = document.getElementById('storyTextInput');
            const text = textInput.value.trim();
            
            if (text) {
                createDraggableText(text);
                textInput.value = '';
                document.getElementById('storyTextInputBottom').style.display = 'none';
                document.getElementById('textToolBtn').classList.remove('active');
            }
        }

        function createDraggableText(text) {
            const textElement = document.createElement('div');
            textElement.className = draggable-text ${currentTextStyle};
            textElement.textContent = text;
            textElement.style.color = currentTextColor;
            textElement.style.fontSize = currentTextSize + 'px';
            textElement.style.left = '50%';
            textElement.style.top = '50%';
            
            // Make draggable
            textElement.addEventListener('mousedown', startDragging);
            textElement.addEventListener('touchstart', startDragging);
            
            // Double click to edit
            textElement.addEventListener('dblclick', editText);
            
            document.getElementById('draggableElements').appendChild(textElement);
            textElements.push(textElement);
        }

        function startDragging(e) {
            draggedElement = e.target;
            const rect = draggedElement.getBoundingClientRect();
            const containerRect = document.querySelector('.preview-content').getBoundingClientRect();
            
            const startX = e.type === 'mousedown' ? e.clientX : e.touches[0].clientX;
            const startY = e.type === 'mousedown' ? e.clientY : e.touches[0].clientY;
            
            function drag(e) {
                const currentX = e.type === 'mousemove' ? e.clientX : e.touches[0].clientX;
                const currentY = e.type === 'mousemove' ? e.clientY : e.touches[0].clientY;
                
                const deltaX = currentX - startX;
                const deltaY = currentY - startY;
                
                const newLeft = ((rect.left + deltaX - containerRect.left) / containerRect.width) * 100;
                const newTop = ((rect.top + deltaY - containerRect.top) / containerRect.height) * 100;
                
                draggedElement.style.left = Math.max(10, Math.min(90, newLeft)) + '%';
                draggedElement.style.top = Math.max(10, Math.min(90, newTop)) + '%';
            }
            
            function stopDragging() {
                document.removeEventListener('mousemove', drag);
                document.removeEventListener('mouseup', stopDragging);
                document.removeEventListener('touchmove', drag);
                document.removeEventListener('touchend', stopDragging);
                draggedElement = null;
            }
            
            document.addEventListener('mousemove', drag);
            document.addEventListener('mouseup', stopDragging);
            document.addEventListener('touchmove', drag);
            document.addEventListener('touchend', stopDragging);
        }

        function editText(e) {
            const element = e.target;
            const currentText = element.textContent;
            const newText = prompt('Edit teks:', currentText);
            if (newText !== null && newText.trim()) {
                element.textContent = newText.trim();
            }
        }

        // Color picker functionality
        document.addEventListener('DOMContentLoaded', function() {
            document.querySelectorAll('.color-btn').forEach(btn => {
                btn.addEventListener('click', function() {
                    currentTextColor = this.dataset.color;
                    
                    // Update active color
                    document.querySelectorAll('.color-btn').forEach(b => b.classList.remove('active'));
                    this.classList.add('active');
                });
            });
        });

        function saveStoryDraft() {
            // Save story as draft (placeholder)
            alert('Story disimpan sebagai draft!');
        }

        function toggleStoryPrivacy() {
            const btn = document.getElementById('privacyBtn');
            if (storyPrivacy === 'public') {
                storyPrivacy = 'close_friends';
                btn.innerHTML = '<span class="btn-icon">👥</span>';
                btn.style.background = '#00d924';
            } else {
                storyPrivacy = 'public';
                btn.innerHTML = '<span class="btn-icon">👁</span>';
                btn.style.background = 'rgba(0, 0, 0, 0.5)';
            }
        }

        function shareToStory(type) {
            // Collect all text elements data
            const storyData = {
                image: document.getElementById('previewImage').src,
                textElements: textElements.map(el => ({
                    text: el.textContent,
                    left: el.style.left,
                    top: el.style.top,
                    color: el.style.color,
                    fontSize: el.style.fontSize,
                    className: el.className
                })),
                type: type
            };
            
            // Add to stories data
            const currentUser = storiesData[0];
            const newStory = {
                image: storyData.image,
                timestamp: 'Sekarang',
                textElements: storyData.textElements,
                type: type
            };
            
            if (!currentUser.stories) {
                currentUser.stories = [];
            }
            
            currentUser.stories.unshift(newStory);
            currentUser.has_story = true;
            
            // Update UI
            updateCurrentUserStoryRing();
            
            // Close modal and show success
            closeAddStory();
            showSuccessModal();
        }

        function showSendStoryModal() {
            alert('Fitur kirim story ke teman akan segera hadir!');
        }

        // Add Story Functions
        function openAddStory() {
            const modal = document.getElementById('addStoryModal');
            modal.classList.add('active');
            setupDragAndDrop();
        }

        function closeAddStory() {
            const modal = document.getElementById('addStoryModal');
            modal.classList.remove('active');
            
            // Reset form
            document.getElementById('photoUploadArea').style.display = 'flex';
            document.getElementById('storyPreview').style.display = 'none';
            document.getElementById('storyPhotoInput').value = '';
            document.getElementById('storyTextInputBottom').style.display = 'none';
            document.getElementById('textToolBtn').classList.remove('active');
            
            // Reset text elements
            textElements = [];
            document.getElementById('draggableElements').innerHTML = '';
            
            // Reset privacy
            storyPrivacy = 'public';
            const privacyBtn = document.getElementById('privacyBtn');
            if (privacyBtn) {
                privacyBtn.innerHTML = '<span class="btn-icon">👁</span>';
                privacyBtn.style.background = 'rgba(0, 0, 0, 0.5)';
            }
        }

        function setupDragAndDrop() {
            const uploadArea = document.getElementById('photoUploadArea');
            
            ['dragenter', 'dragover', 'dragleave', 'drop'].forEach(eventName => {
                uploadArea.addEventListener(eventName, preventDefaults, false);
            });

            function preventDefaults(e) {
                e.preventDefault();
                e.stopPropagation();
            }

            ['dragenter', 'dragover'].forEach(eventName => {
                uploadArea.addEventListener(eventName, () => uploadArea.classList.add('dragover'), false);
            });

            ['dragleave', 'drop'].forEach(eventName => {
                uploadArea.addEventListener(eventName, () => uploadArea.classList.remove('dragover'), false);
            });

            uploadArea.addEventListener('drop', handleDrop, false);
        }

        function handleDrop(e) {
            const dt = e.dataTransfer;
            const files = dt.files;
            handleFiles(files);
        }

        function handleFiles(files) {
            if (files.length > 0) {
                const file = files[0];
                if (file.type.startsWith('image/')) {
                    displayImagePreview(file);
                }
            }
        }

        function displayImagePreview(file) {
            const reader = new FileReader();
            reader.onload = function(e) {
                document.getElementById('previewImage').src = e.target.result;
                document.getElementById('photoUploadArea').style.display = 'none';
                document.getElementById('storyPreview').style.display = 'block';
                
                // Reset text elements
                textElements = [];
                document.getElementById('draggableElements').innerHTML = '';
            };
            reader.readAsDataURL(file);
        }

        // Handle file input change
        document.getElementById('storyPhotoInput').addEventListener('change', function(e) {
            if (e.target.files.length > 0) {
                displayImagePreview(e.target.files[0]);
            }
        });

        function cancelStory() {
            document.getElementById('photoUploadArea').style.display = 'flex';
            document.getElementById('storyPreview').style.display = 'none';
            document.getElementById('storyText').value = '';
        }

        function changeTextColor() {
            const colors = ['white', '#ff3040', '#0095f6', '#00d924', '#ffcc00', '#ff6b35'];
            const currentIndex = colors.indexOf(currentTextColor);
            const nextIndex = (currentIndex + 1) % colors.length;
            currentTextColor = colors[nextIndex];
            
            const textarea = document.getElementById('storyText');
            textarea.style.color = currentTextColor;
        }

        function changeTextSize() {
            const sizes = [18, 24, 30, 36];
            const currentIndex = sizes.indexOf(currentTextSize);
            const nextIndex = (currentIndex + 1) % sizes.length;
            currentTextSize = sizes[nextIndex];
            
            const textarea = document.getElementById('storyText');
            textarea.style.fontSize = currentTextSize + 'px';
        }

        function postStory() {
            const imageData = document.getElementById('previewImage').src;
            const storyText = document.getElementById('storyText').value;
            
            // Add new story to current user's stories
            const currentUser = storiesData[0]; // First item is current user
            const newStory = {
                image: imageData,
                timestamp: 'Sekarang',
                text: storyText,
                textColor: currentTextColor,
                textSize: currentTextSize
            };
            
            if (!currentUser.stories) {
                currentUser.stories = [];
            }
            
            currentUser.stories.unshift(newStory); // Add to beginning
            currentUser.has_story = true;
            
            // Update UI
            updateCurrentUserStoryRing();
            
            // Close add story modal
            closeAddStory();
            
            // Show success modal
            showSuccessModal();
        }

        function updateCurrentUserStoryRing() {
            const currentUserElement = document.querySelector('[data-story-index="0"] .story-ring');
            if (currentUserElement) {
                currentUserElement.classList.remove('add-story');
                currentUserElement.classList.add('has-story');
                
                // Change onclick to open story instead of add story
                const highlightItem = currentUserElement.parentElement;
                highlightItem.setAttribute('onclick', 'openStory(0)');
                
                // Update username text
                const usernameElement = highlightItem.querySelector('.highlight-username');
                usernameElement.textContent = 'wellysaverdalena';
                
                // Remove plus icon
                const plusIcon = currentUserElement.querySelector('.add-story-plus');
                if (plusIcon) {
                    plusIcon.remove();
                }
            }
        }

        function showSuccessModal() {
            const modal = document.getElementById('storySuccessModal');
            modal.classList.add('active');
            
            // Auto close after 3 seconds
            setTimeout(() => {
                closeSuccessModal();
            }, 3000);
        }

        function closeSuccessModal() {
            const modal = document.getElementById('storySuccessModal');
            modal.classList.remove('active');
        }

        function openStory(userIndex) {
            currentUserIndex = userIndex;
            currentStoryIndex = 0;
            
            const modal = document.getElementById('storyModal');
            modal.classList.add('active');
            
            // Mark story as viewed
            const storyRing = document.querySelector([data-story-index="${userIndex}"] .story-ring);
            if (storyRing) {
                storyRing.classList.add('viewed');
            }
            
            showStory();
            document.addEventListener('keydown', handleKeyPress);
        }

        function closeStory() {
            const modal = document.getElementById('storyModal');
            modal.classList.remove('active');
            
            clearTimeout(storyTimer);
            clearInterval(progressTimer);
            document.removeEventListener('keydown', handleKeyPress);
        }

        function showStory() {
            const user = storiesData[currentUserIndex];
            const story = user.stories[currentStoryIndex];
            
            // Update story content
            document.getElementById('storyUserAvatar').src = user.avatar;
            document.getElementById('storyUsername').textContent = user.username;
            document.getElementById('storyTimestamp').textContent = story.timestamp;
            document.getElementById('storyImage').src = story.image;
            
            // Add text overlay if story has text
            let textOverlay = document.querySelector('.story-text-display');
            if (textOverlay) {
                textOverlay.remove();
            }
            
            if (story.text && story.text.trim() !== '') {
                textOverlay = document.createElement('div');
                textOverlay.className = 'story-text-display';
                textOverlay.style.cssText = `
                    position: absolute;
                    bottom: 120px;
                    left: 20px;
                    right: 20px;
                    text-align: center;
                    font-size: ${story.textSize || 18}px;
                    color: ${story.textColor || 'white'};
                    font-weight: bold;
                    text-shadow: 2px 2px 4px rgba(0,0,0,0.8);
                    z-index: 3;
                    word-wrap: break-word;
                `;
                textOverlay.textContent = story.text;
                document.querySelector('.story-content').appendChild(textOverlay);
            }
            
            // Create progress bars
            createProgressBars();
            
            // Start story timer
            startStoryProgress();
        }

        function createProgressBars() {
            const user = storiesData[currentUserIndex];
            const progressContainer = document.querySelector('.story-progress-bars');
            progressContainer.innerHTML = '';
            
            user.stories.forEach((_, index) => {
                const progressBar = document.createElement('div');
                progressBar.className = 'story-progress-bar';
                
                const progressFill = document.createElement('div');
                progressFill.className = 'story-progress-fill';
                
                if (index < currentStoryIndex) {
                    progressFill.style.width = '100%';
                } else if (index === currentStoryIndex) {
                    progressFill.style.width = '0%';
                } else {
                    progressFill.style.width = '0%';
                }
                
                progressBar.appendChild(progressFill);
                progressContainer.appendChild(progressBar);
            });
        }

        function startStoryProgress() {
            clearTimeout(storyTimer);
            clearInterval(progressTimer);
            
            const progressFill = document.querySelectorAll('.story-progress-fill')[currentStoryIndex];
            let progress = 0;
            const duration = 5000; // 5 seconds
            const interval = 50; // Update every 50ms
            const increment = (interval / duration) * 100;
            
            progressTimer = setInterval(() => {
                progress += increment;
                if (progressFill) {
                    progressFill.style.width = Math.min(progress, 100) + '%';
                }
                
                if (progress >= 100) {
                    clearInterval(progressTimer);
                    nextStory();
                }
            }, interval);
        }

        function nextStory() {
            const user = storiesData[currentUserIndex];
            
            if (currentStoryIndex < user.stories.length - 1) {
                currentStoryIndex++;
                showStory();
            } else {
                // Move to next user or close if last user
                if (currentUserIndex < storiesData.length - 1) {
                    currentUserIndex++;
                    currentStoryIndex = 0;
                    showStory();
                } else {
                    closeStory();
                }
            }
        }

        function previousStory() {
            if (currentStoryIndex > 0) {
                currentStoryIndex--;
                showStory();
            } else if (currentUserIndex > 0) {
                currentUserIndex--;
                const user = storiesData[currentUserIndex];
                currentStoryIndex = user.stories.length - 1;
                showStory();
            }
        }

        function handleKeyPress(event) {
            switch(event.key) {
                case 'Escape':
                    closeStory();
                    break;
                case 'ArrowLeft':
                    previousStory();
                    break;
                case 'ArrowRight':
                case ' ':
                    event.preventDefault();
                    nextStory();
                    break;
            }
        }

        // Close modal when clicking outside
        document.getElementById('storyModal').addEventListener('click', function(e) {
            if (e.target === this) {
                closeStory();
            }
        });

        // Pause story on mouse hold
        let isPaused = false;
        document.querySelector('.story-container').addEventListener('mousedown', function() {
            isPaused = true;
            clearInterval(progressTimer);
        });

        document.querySelector('.story-container').addEventListener('mouseup', function() {
            if (isPaused) {
                isPaused = false;
                startStoryProgress();
            }
        });
    </script>

    <?php
    require_once __DIR__ . '/../../includes/footer.php';
    ?>
