<?php

// Tampilkan header
require_once __DIR__ . '/../../includes/header.php';

// Call modal post
require_once __DIR__ . '/../../models/Post.php';

// Ambil semua post
$posts = getAllPosts();

// Sample data for stories and suggestions
$stories = [
    [
        'username' => '_dwiirhma', 
        'is_current_user' => true,
        'avatar' => '../../public/img/gambar1.jpg',
        'stories' => [
            ['image' => '../../public/img/gambar3.jpg', 'timestamp' => '2 jam'],
            ['image' => '../../public/img/gambar4.jpg', 'timestamp' => '4 jam']
        ],
        'has_story' => true
    ],
    [
        'username' => '_8lololowme', 
        'avatar' => '../../public/img/jamet.jpg',
        'stories' => [
            ['image' => '../../public/img/gambar4.jpg', 'timestamp' => '1 jam'],
            ['image' => '../../public/img/gambar5.jpg', 'timestamp' => '3 jam'],
            ['image' => '../../public/img/gambar6.jpg', 'timestamp' => '5 jam']
        ],
        'has_story' => true
    ],
    [
        'username' => 'dumphileee', 
        'avatar' => '../../public/img/dumphileee.jpg',
        'stories' => [
            ['image' => '../../public/img/gambar6.jpg', 'timestamp' => '30 menit']
        ],
        'has_story' => true
    ],
    [
        'username' => 'arinassjj', 
        'avatar' => '../../public/img/arin.jpg',
        'stories' => [
            ['image' => '../../public/img/gambar5.jpg', 'timestamp' => '6 jam']
        ],
        'has_story' => true
    ],
    [
        'username' => 'wijaayakusuma', 
        'avatar' => '../../public/img/jaya.jpg',
        'stories' => [
            ['image' => '../../public/img/gambar7.jpg', 'timestamp' => '8 jam'],
            ['image' => '../../public/img/gambar8.jpg', 'timestamp' => '10 jam']
        ],
        'has_story' => true
    ],
    [
        'username' => 'my2ndpagee_', 
        'avatar' => '../../public/img/nina.jpg',
        'stories' => [
            ['image' => '../../public/img/gambar9.jpg', 'timestamp' => '12 jam']
        ],
        'has_story' => true
    ]
];

$suggestions = [
    ['username' => 'houseoffchilll', 'avatar' => '../../public/img/houseofchill.jpg','mutual' => 'Disarankan untuk Anda'],
    ['username' => 'aliviaa_putrii', 'avatar' => '../../public/img/lipia.jpg', 'mutual' => 'Disarankan untuk Anda'],
    ['username' => 'odyssmt_', 'avatar' => '../../public/img/ody.jpg', 'mutual' => 'Disarankan untuk Anda'],
    ['username' => 'oktaviatamd_', 'avatar' => '../../public/img/manda.jpg', 'mutual' => 'Diikuti oleh mamanx_x'],
    ['username' => 'whysetia_', 'avatar' => '../../public/img/wahyu.jpg', 'mutual' => 'Diikuti oleh fajridn_']
];

function renderHighlightsSection($stories) {
    ?>
    <div class="highlights-section">
        <div class="highlights-container">
            <?php foreach ($stories as $index => $story): ?>
                <div class="highlight-item" data-story-index="<?= $index ?>">
                    <?php if (isset($story['is_current_user']) && $story['is_current_user']): ?>
                        <!-- Add Story Button for Current User -->
                        <div class="story-ring add-story" onclick="openAddStory()">
                            <img src="<?= htmlspecialchars($story['avatar']) ?>" alt="<?= htmlspecialchars($story['username']) ?>" class="highlight-avatar">
                            <div class="add-story-plus">+</div>
                        </div>
                        <span class="highlight-username">Story Anda</span>
                    <?php else: ?>
                        <div class="story-ring <?= $story['has_story'] ? 'has-story' : '' ?>" onclick="openStory(<?= $index ?>)">
                            <img src="<?= htmlspecialchars($story['avatar']) ?>" alt="<?= htmlspecialchars($story['username']) ?>" class="highlight-avatar">
                        </div>
                        <span class="highlight-username"><?= htmlspecialchars($story['username']) ?></span>
                    <?php endif; ?>
                </div>
            <?php endforeach; ?>
        </div>
    </div>

    <!-- Story Modal -->
    <div id="storyModal" class="story-modal">
        <div class="story-container">
            <div class="story-header">
                <div class="story-progress-bars">
                    <!-- Progress bars will be generated by JavaScript -->
                </div>
                <div class="story-user-info">
                    <img id="storyUserAvatar" src="" alt="" class="story-user-avatar">
                    <span id="storyUsername"></span>
                    <span id="storyTimestamp" class="story-timestamp"></span>
                </div>
                <button class="story-close" onclick="closeStory()">×</button>
            </div>
            
            <div class="story-content">
                <img id="storyImage" src="" alt="Story">
                <div class="story-navigation">
                    <div class="story-prev" onclick="previousStory()"></div>
                    <div class="story-next" onclick="nextStory()"></div>
                </div>
            </div>
            
            <div class="story-actions">
                <input type="text" placeholder="Kirim pesan" class="story-message-input">
                <button class="story-heart">❤</button>
                <button class="story-share">📤</button>
            </div>
        </div>
    </div>

    <!-- Add Story Modal -->
    <div id="addStoryModal" class="story-modal add-story-modal">
        <div class="add-story-container">
            <div class="add-story-header">
                <h3>Buat story</h3>
                <button class="story-close" onclick="closeAddStory()">×</button>
            </div>
            
            <!-- Photo Upload Area -->
            <div class="photo-upload-area" id="photoUploadArea">
                <div class="upload-placeholder">
                    <div class="upload-icon">📷</div>
                    <h3>Pilih foto untuk story</h3>
                    <p>Klik untuk memilih foto atau drag & drop</p>
                    <input type="file" id="storyPhotoInput" accept="image/*" style="display: none;">
                    <button class="upload-btn" onclick="document.getElementById('storyPhotoInput').click()">
                        Pilih Foto
                    </button>
                </div>
            </div>

            <!-- Story Preview -->
            <div class="story-preview" id="storyPreview" style="display: none;">
                <!-- Story Tools Header -->
                <div class="story-tools-header">
                    <button class="story-tool-btn" onclick="closeAddStory()">✕</button>
                    <button class="story-tool-btn" onclick="toggleBoomerang()">∞</button>
                    <button class="story-tool-btn" onclick="addText()" id="textToolBtn">Aa</button>
                    <button class="story-tool-btn" onclick="addSticker()">😊</button>
                    <button class="story-tool-btn" onclick="addMusic()">♪</button>
                    <button class="story-tool-btn" onclick="addSparkles()">✨</button>
                    <button class="story-tool-btn more-tools" onclick="showMoreTools()">⋯</button>
                </div>
                
                <div class="preview-content">
                    <img id="previewImage" src="" alt="Story Preview">
                    <!-- Draggable text elements will be added here -->
                    <div class="draggable-elements" id="draggableElements"></div>
                </div>
                
                <!-- Bottom Text Input -->
                <div class="story-text-input-bottom" id="storyTextInputBottom" style="display: none;">
                    <input type="text" id="storyTextInput" placeholder="Tambahkan keterangan..." maxlength="100">
                    <div class="text-style-options">
                        <button class="text-style-btn" onclick="changeTextStyle('classic')" data-style="classic">A</button>
                        <button class="text-style-btn" onclick="changeTextStyle('modern')" data-style="modern">𝗔</button>
                        <button class="text-style-btn" onclick="changeTextStyle('neon')" data-style="neon">𝔸</button>
                        <button class="text-style-btn" onclick="changeTextStyle('typewriter')" data-style="typewriter">𝙰</button>
                    </div>
                    <div class="text-color-options">
                        <div class="color-picker">
                            <button class="color-btn" data-color="white" style="background: white; border: 2px solid #333;"></button>
                            <button class="color-btn" data-color="#ff3040" style="background: #ff3040;"></button>
                            <button class="color-btn" data-color="#0095f6" style="background: #0095f6;"></button>
                            <button class="color-btn" data-color="#00d924" style="background: #00d924;"></button>
                            <button class="color-btn" data-color="#ffcc00" style="background: #ffcc00;"></button>
                            <button class="color-btn" data-color="#ff6b35" style="background: #ff6b35;"></button>
                            <button class="color-btn" data-color="#8a2be2" style="background: #8a2be2;"></button>
                            <button class="color-btn" data-color="#ff1493" style="background: #ff1493;"></button>
                        </div>
                    </div>
                    <button class="done-text-btn" onclick="addTextToStory()">Selesai</button>
                </div>
                
                <!-- Bottom Story Actions -->
                <div class="story-bottom-actions">
                    <div class="story-bottom-left">
                        <button class="bottom-action-btn" onclick="saveStoryDraft()">
                            <span class="btn-icon">💾</span>
                        </button>
                        <button class="bottom-action-btn" onclick="toggleStoryPrivacy()" id="privacyBtn">
                            <span class="btn-icon">👁</span>
                        </button>
                    </div>
                    
                    <div class="story-bottom-center">
                        <div class="share-options">
                            <div class="share-option" onclick="shareToStory('story')">
                                <div class="share-avatar">
                                    <img src="../../public/img/gambar3.jpg" alt="Your Story">
                                </div>
                                <span>Cerita Anda</span>
                            </div>
                            <div class="share-option" onclick="shareToStory('close_friends')">
                                <div class="share-avatar close-friends">
                                    <img src="../../public/img/gambar3.jpg" alt="Close Friends">
                                    <div class="close-friends-badge">⭐</div>
                                </div>
                                <span>Teman Dekat</span>
                            </div>
                        </div>
                    </div>
                    
                    <div class="story-bottom-right">
                        <button class="send-story-btn" onclick="showSendStoryModal()">
                            <span class="send-icon">→</span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Story Success Modal -->
    <div id="storySuccessModal" class="story-modal">
        <div class="success-container">
            <div class="success-content">
                <div class="success-icon">✅</div>
                <h3>Story berhasil dibagikan!</h3>
                <p>Story Anda sekarang dapat dilihat oleh pengikut selama 24 jam</p>
                <button class="success-btn" onclick="closeSuccessModal()">OK</button>
            </div>
        </div>
    </div>
    <?php
}

function renderFeedSection($posts, $stories) {
    ?>
    <div class="section" id="feed">
        <div class="feed-section">
            <!-- Feed Posts -->
            <?php if (!empty($posts)): ?>
                <?php foreach ($posts as $post): ?>
                    <div class="feed-post">
                        <!-- Post Header -->
                        <div class="post-header">
                            <img src="<?= htmlspecialchars($post['avatar'] ?? 'public/img/gambar3.jpg') ?>" alt="<?= htmlspecialchars($post['username']) ?>" class="post-avatar">
                            <a href="#" class="post-username"><?= htmlspecialchars($post['username']) ?></a>
                            <span class="post-time"><?= date('j M', strtotime($post['created_at'] ?? 'now')) ?></span>
                            <button class="post-options">⋯</button>
                        </div>
                        
                        <!-- Post Images (multiple) -->
                        <?php if (!empty($post['image'])): ?>
                            <div class="post-images">
                 <img src="<?= '/public/img/' . htmlspecialchars($post['image']) ?>" alt="Post Image">
                                
                            </div>
                        <?php else: ?>
                            <div class="post-placeholder">
                                <i class="fas fa-camera fa-2x"></i>
                            </div>
                        <?php endif; ?>
                        
                        <!-- Post Actions -->
                        <div class="post-actions">
                            <button class="post-action">❤</button>
                            <button class="post-action">💬</button>
                            <button class="post-action">📤</button>
                            <button class="post-action">🔖</button>
                        </div>
                        
                        <!-- Post Likes & Caption -->
                        <div class="post-content-text">
                            <div class="post-likes">42 suka</div>
                            <div class="post-caption">
                                <span class="username"><?= htmlspecialchars($post['username']) ?></span>
                                <?= htmlspecialchars($post['caption'] ?? '') ?>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php else: ?>
                <div class="no-posts">
                    <i class="fas fa-camera fa-3x mb-3"></i>
                    <h3>Belum ada postingan di feed</h3>
                    <p>Mulai berbagi momen Anda atau ikuti akun lain</p>
                </div>
            <?php endif; ?>
        </div>
    </div>
    <?php
}

function renderRightSidebar($suggestions) {
    ?>
    <div class="sidebar-right">
        <div class="profile-switch">
            <div class="profile-info">
                <form id="formProfilePic" enctype="multipart/form-data">
                    <label for="profilePicInput">
                        <img id="profileAvatar" src="../../public/img/gambar1.jpg" alt="_dwiirhma" class="profile-avatar">
                    </label>
                    <input type="file" id="profilePicInput" name="profile_pic" accept="image/*" style="display:none;">
                </form>
                <div class="profile-details">
                    <h4>_dwiirhma</h4>
                </div>
            </div>
            <button class="switch-btn">Alihkan</button>
        </div>

        <div class="suggestions">
            <div class="suggestions-header">
                <h3 class="suggestions-title">Disarankan untuk Anda</h3>
                <a href="#" class="see-all">Lihat Semua</a>
            </div>
            
            <?php foreach($suggestions as $suggestion): ?>
            <div class="suggestion-item">
                <div class="suggestion-info">
                    <img src="<?php echo $suggestion['avatar']; ?>" alt="<?php echo $suggestion['username']; ?>" class="suggestion-avatar">
                    <div class="suggestion-details">
                        <h5><?php echo $suggestion['username']; ?></h5>
                        <p><?php echo $suggestion['mutual']; ?></p>
                    </div>
                </div>
                <button class="follow-btn">Ikuti</button>
            </div>
            <?php endforeach; ?>
        </div>

        <div class="footer">
            <div class="footer-links">
                <a href="#">Tentang</a> • 
                <a href="#">Bantuan</a> • 
                <a href="#">Pers</a> • 
                <a href="#">API</a> • 
                <a href="#">Pekerjaan</a> • 
                <a href="#">Privasi</a> • 
                <a href="#">Ketentuan</a> • 
                <a href="#">Lokasi</a> • 
                <a href="#">Bahasa</a> • 
                <a href="#">Verifikasi Meta</a>
            </div>
            <p>© 2025 INSTAGRAM FROM META</p>
        </div>
    </div>
    <?php
}
?>

    <div class="instagram-container">
        <!-- Main Content -->
        <main class="main-content">
            <?php renderHighlightsSection($stories); ?>
            <?php renderFeedSection($posts, $stories); ?>
        </main>
        
        <?php renderRightSidebar($suggestions); ?>
    </div>

   

    <!-- <script src="modules/home/instagram.js"></script> -->
</div>
     <script>

        // Membungkus semua kode di dalam DOMContentLoaded untuk memastikan semua elemen HTML siap
        document.addEventListener('DOMContentLoaded', function() {
            // Story data from PHP
            const storiesData = <?= json_encode($stories) ?>;
            let currentUserIndex = 0;
            let currentStoryIndex = 0;
            let storyTimer;
            let progressTimer;
            let currentTextColor = 'white';
            let currentTextSize = 18;
            let currentTextStyle = 'classic';
            let draggedElement = null;
            let textElements = [];
            let storyPrivacy = 'public'; // public or close_friends

            // Story Tools Functions
            window.toggleBoomerang = function() {
                // Toggle boomerang effect (placeholder)
                const btn = event.target;
                btn.classList.toggle('active');
            }

            window.addText = function() {
                const textInput = document.getElementById('storyTextInputBottom');
                const isVisible = textInput.style.display !== 'none';
                
                if (isVisible) {
                    textInput.style.display = 'none';
                    document.getElementById('textToolBtn').classList.remove('active');
                } else {
                    textInput.style.display = 'block';
                    document.getElementById('textToolBtn').classList.add('active');
                    document.getElementById('storyTextInput').focus();
                }
            }

            window.addSticker = function() {
                alert('Fitur sticker akan segera hadir!');
            }

            window.addMusic = function() {
                alert('Fitur musik akan segera hadir!');
            }

            window.addSparkles = function() {
                alert('Fitur efek akan segera hadir!');
            }

            window.showMoreTools = function() {
                alert('Lebih banyak tools akan segera hadir!');
            }

            window.changeTextStyle = function(style) {
                currentTextStyle = style;
                
                // Update active button
                document.querySelectorAll('.text-style-btn').forEach(btn => {
                    btn.classList.remove('active');
                });
                // PERBAIKAN: Menggunakan template literal untuk querySelector yang benar
                document.querySelector(`[data-style="${style}"]`).classList.add('active');
            }

            window.addTextToStory = function() {
                const textInput = document.getElementById('storyTextInput');
                const text = textInput.value.trim();
                
                if (text) {
                    createDraggableText(text);
                    textInput.value = '';
                    document.getElementById('storyTextInputBottom').style.display = 'none';
                    document.getElementById('textToolBtn').classList.remove('active');
                }
            }

            function createDraggableText(text) {
                const textElement = document.createElement('div');
                // PERBAIKAN: Menggunakan template literal untuk className
                textElement.className = `draggable-text ${currentTextStyle}`;
                textElement.textContent = text;
                textElement.style.color = currentTextColor;
                textElement.style.fontSize = currentTextSize + 'px';
                textElement.style.left = '50%';
                textElement.style.top = '50%';
                
                textElement.addEventListener('mousedown', startDragging);
                textElement.addEventListener('touchstart', startDragging);
                textElement.addEventListener('dblclick', editText);
                
                document.getElementById('draggableElements').appendChild(textElement);
                textElements.push(textElement);
            }

            function startDragging(e) {
                draggedElement = e.target;
                const rect = draggedElement.getBoundingClientRect();
                const containerRect = document.querySelector('.preview-content').getBoundingClientRect();
                
                const startX = e.type === 'mousedown' ? e.clientX : e.touches[0].clientX;
                const startY = e.type === 'mousedown' ? e.clientY : e.touches[0].clientY;
                
                function drag(ev) {
                    const currentX = ev.type === 'mousemove' ? ev.clientX : ev.touches[0].clientX;
                    const currentY = ev.type === 'mousemove' ? ev.clientY : ev.touches[0].clientY;
                    
                    const deltaX = currentX - startX;
                    const deltaY = currentY - startY;
                    
                    const newLeft = ((rect.left + deltaX - containerRect.left) / containerRect.width) * 100;
                    const newTop = ((rect.top + deltaY - containerRect.top) / containerRect.height) * 100;
                    
                    draggedElement.style.left = Math.max(10, Math.min(90, newLeft)) + '%';
                    draggedElement.style.top = Math.max(10, Math.min(90, newTop)) + '%';
                }
                
                function stopDragging() {
                    document.removeEventListener('mousemove', drag);
                    document.removeEventListener('mouseup', stopDragging);
                    document.removeEventListener('touchmove', drag);
                    document.removeEventListener('touchend', stopDragging);
                    draggedElement = null;
                }
                
                document.addEventListener('mousemove', drag);
                document.addEventListener('mouseup', stopDragging);
                document.addEventListener('touchmove', drag);
                document.addEventListener('touchend', stopDragging);
            }

            function editText(e) {
                const element = e.target;
                const currentText = element.textContent;
                const newText = prompt('Edit teks:', currentText);
                if (newText !== null && newText.trim()) {
                    element.textContent = newText.trim();
                }
            }

            document.querySelectorAll('.color-btn').forEach(btn => {
                btn.addEventListener('click', function() {
                    currentTextColor = this.dataset.color;
                    document.querySelectorAll('.color-btn').forEach(b => b.classList.remove('active'));
                    this.classList.add('active');
                });
            });

            window.saveStoryDraft = function() {
                alert('Story disimpan sebagai draft!');
            }

            window.toggleStoryPrivacy = function() {
                const btn = document.getElementById('privacyBtn');
                if (storyPrivacy === 'public') {
                    storyPrivacy = 'close_friends';
                    btn.innerHTML = '<span class="btn-icon">👥</span>';
                    btn.style.background = '#00d924';
                } else {
                    storyPrivacy = 'public';
                    btn.innerHTML = '<span class="btn-icon">👁</span>';
                    btn.style.background = 'rgba(0, 0, 0, 0.5)';
                }
            }

            window.shareToStory = function(type) {
                const storyData = {
                    image: document.getElementById('previewImage').src,
                    textElements: textElements.map(el => ({
                        text: el.textContent,
                        left: el.style.left,
                        top: el.style.top,
                        color: el.style.color,
                        fontSize: el.style.fontSize,
                        className: el.className
                    })),
                    type: type
                };
                
                const currentUser = storiesData[0];
                const newStory = {
                    image: storyData.image,
                    timestamp: 'Sekarang',
                    textElements: storyData.textElements,
                    type: type
                };
                
                if (!currentUser.stories) currentUser.stories = [];
                
                currentUser.stories.unshift(newStory);
                currentUser.has_story = true;
                
                updateCurrentUserStoryRing();
                closeAddStory();
                showSuccessModal();
            }

            window.showSendStoryModal = function() {
                alert('Fitur kirim story ke teman akan segera hadir!');
            }

            window.openAddStory = function() {
                document.getElementById('addStoryModal').classList.add('active');
                setupDragAndDrop();
            }

            window.closeAddStory = function() {
                const modal = document.getElementById('addStoryModal');
                modal.classList.remove('active');
                
                document.getElementById('photoUploadArea').style.display = 'flex';
                document.getElementById('storyPreview').style.display = 'none';
                document.getElementById('storyPhotoInput').value = '';
                document.getElementById('storyTextInputBottom').style.display = 'none';
                document.getElementById('textToolBtn').classList.remove('active');
                
                textElements = [];
                document.getElementById('draggableElements').innerHTML = '';
                
                storyPrivacy = 'public';
                const privacyBtn = document.getElementById('privacyBtn');
                if (privacyBtn) {
                    privacyBtn.innerHTML = '<span class="btn-icon">👁</span>';
                    privacyBtn.style.background = 'rgba(0, 0, 0, 0.5)';
                }
            }

            function setupDragAndDrop() {
                const uploadArea = document.getElementById('photoUploadArea');
                
                ['dragenter', 'dragover', 'dragleave', 'drop'].forEach(eventName => {
                    uploadArea.addEventListener(eventName, preventDefaults, false);
                });

                function preventDefaults(e) {
                    e.preventDefault();
                    e.stopPropagation();
                }

                ['dragenter', 'dragover'].forEach(eventName => {
                    uploadArea.addEventListener(eventName, () => uploadArea.classList.add('dragover'), false);
                });

                ['dragleave', 'drop'].forEach(eventName => {
                    uploadArea.addEventListener(eventName, () => uploadArea.classList.remove('dragover'), false);
                });

                uploadArea.addEventListener('drop', handleDrop, false);
            }

            function handleDrop(e) {
                const dt = e.dataTransfer;
                const files = dt.files;
                handleFiles(files);
            }

            function handleFiles(files) {
                if (files.length > 0 && files[0].type.startsWith('image/')) {
                    displayImagePreview(files[0]);
                }
            }

            function displayImagePreview(file) {
                const reader = new FileReader();
                reader.onload = function(e) {
                    document.getElementById('previewImage').src = e.target.result;
                    document.getElementById('photoUploadArea').style.display = 'none';
                    document.getElementById('storyPreview').style.display = 'block';
                    
                    textElements = [];
                    document.getElementById('draggableElements').innerHTML = '';
                };
                reader.readAsDataURL(file);
            }

            document.getElementById('storyPhotoInput').addEventListener('change', function(e) {
                if (e.target.files.length > 0) {
                    displayImagePreview(e.target.files[0]);
                }
            });

            function updateCurrentUserStoryRing() {
                const currentUserElement = document.querySelector('[data-story-index="0"] .story-ring');
                if (currentUserElement) {
                    currentUserElement.classList.remove('add-story');
                    currentUserElement.classList.add('has-story');
                    
                    const highlightItem = currentUserElement.parentElement;
                    highlightItem.setAttribute('onclick', 'openStory(0)');
                    
                    const usernameElement = highlightItem.querySelector('.highlight-username');
                    usernameElement.textContent = storiesData[0].username;
                    
                    const plusIcon = currentUserElement.querySelector('.add-story-plus');
                    if (plusIcon) plusIcon.remove();
                }
            }

            function showSuccessModal() {
                document.getElementById('storySuccessModal').classList.add('active');
                setTimeout(closeSuccessModal, 3000);
            }

            window.closeSuccessModal = function() {
                document.getElementById('storySuccessModal').classList.remove('active');
            }

            window.openStory = function(userIndex) {
                currentUserIndex = userIndex;
                currentStoryIndex = 0;
                
                document.getElementById('storyModal').classList.add('active');
                
                // PERBAIKAN: Menggunakan template literal untuk querySelector yang benar
                const storyRing = document.querySelector(`[data-story-index="${userIndex}"] .story-ring`);
                if (storyRing) {
                    storyRing.classList.add('viewed');
                }
                
                showStory();
                document.addEventListener('keydown', handleKeyPress);
            }

            window.closeStory = function() {
                document.getElementById('storyModal').classList.remove('active');
                clearTimeout(storyTimer);
                clearInterval(progressTimer);
                document.removeEventListener('keydown', handleKeyPress);
            }

            function showStory() {
                const user = storiesData[currentUserIndex];
                if (!user || !user.stories || user.stories.length === 0) {
                    closeStory();
                    return;
                }
                const story = user.stories[currentStoryIndex];
                
                document.getElementById('storyUserAvatar').src = user.avatar;
                document.getElementById('storyUsername').textContent = user.username;
                document.getElementById('storyTimestamp').textContent = story.timestamp;
                document.getElementById('storyImage').src = story.image;
                
                createProgressBars();
                startStoryProgress();
            }

            function createProgressBars() {
                const user = storiesData[currentUserIndex];
                const progressContainer = document.querySelector('.story-progress-bars');
                progressContainer.innerHTML = '';
                
                user.stories.forEach((_, index) => {
                    const progressBar = document.createElement('div');
                    progressBar.className = 'story-progress-bar';
                    const progressFill = document.createElement('div');
                    progressFill.className = 'story-progress-fill';
                    
                    if (index < currentStoryIndex) {
                        progressFill.style.width = '100%';
                    }
                    
                    progressBar.appendChild(progressFill);
                    progressContainer.appendChild(progressBar);
                });
            }

            function startStoryProgress() {
                clearTimeout(storyTimer);
                clearInterval(progressTimer);
                
                const progressFillElements = document.querySelectorAll('.story-progress-fill');
                if (progressFillElements.length <= currentStoryIndex) return;

                const progressFill = progressFillElements[currentStoryIndex];
                let progress = 0;
                const duration = 5000;
                const interval = 50;
                const increment = (interval / duration) * 100;
                
                progressTimer = setInterval(() => {
                    if (isPaused) return;
                    progress += increment;
                    progressFill.style.width = Math.min(progress, 100) + '%';
                    
                    if (progress >= 100) {
                        clearInterval(progressTimer);
                        nextStory();
                    }
                }, interval);
            }

            window.nextStory = function() {
                const user = storiesData[currentUserIndex];
                if (currentStoryIndex < user.stories.length - 1) {
                    currentStoryIndex++;
                    showStory();
                } else {
                    if (currentUserIndex < storiesData.length - 1) {
                        currentUserIndex++;
                        currentStoryIndex = 0;
                        showStory();
                    } else {
                        closeStory();
                    }
                }
            }

            window.previousStory = function() {
                if (currentStoryIndex > 0) {
                    currentStoryIndex--;
                    showStory();
                } else if (currentUserIndex > 0) {
                    currentUserIndex--;
                    const user = storiesData[currentUserIndex];
                    currentStoryIndex = user.stories ? user.stories.length - 1 : 0;
                    showStory();
                }
            }

            function handleKeyPress(event) {
                switch(event.key) {
                    case 'Escape': closeStory(); break;
                    case 'ArrowLeft': previousStory(); break;
                    case 'ArrowRight': case ' ': event.preventDefault(); nextStory(); break;
                }
            }

            document.getElementById('storyModal').addEventListener('click', function(e) {
                if (e.target === this) closeStory();
            });

            document.querySelector('.story-container').addEventListener('mousedown', function() {
                isPaused = true;
            });

            document.querySelector('.story-container').addEventListener('mouseup', function() {
                isPaused = false;
            });
            document.querySelector('.story-container').addEventListener('mouseleave', function() {
                isPaused = false;
            });
        });
    </script>

<?php
    require_once __DIR__ . '/../../includes/footer.php';
?>