<?php
// modules/instagram/instagram.php
session_start();
// Tampilkan header
require_once __DIR__ . '/../../includes/header.php';
// Call modal post
require_once __DIR__ . '/../../models/Post.php';

// get user_id
$user_id = isset($_SESSION['user']['id']) ? intval($_SESSION['user']['id']) : 0;

// Ambil semua post
$posts = getAllPosts($user_id);

// Sample data for stories and suggestions
$stories = [
    [
        'username' => '_dwiirhma', 
        'is_current_user' => true,
        'avatar' => '../../public/img/gambar1.jpg',
        'stories' => [
            ['image' => '../../public/img/gambar3.jpg', 'timestamp' => '2 jam'],
            ['image' => '../../public/img/gambar4.jpg', 'timestamp' => '4 jam']
        ],
        'has_story' => true
    ],
    [
        'username' => '_8lololowme', 
        'avatar' => '../../public/img/jamet.jpg',
        'stories' => [
            ['image' => '../../public/img/jamet.jpg', 'timestamp' => '1 jam'],
            ['image' => '../../public/img/jamet.jpg', 'timestamp' => '3 jam'],
            ['image' => '../../public/img/jamet.jpg', 'timestamp' => '5 jam']
        ],
        'has_story' => true
    ],
    [
        'username' => 'dumphileee', 
        'avatar' => '../../public/img/dumphileee.jpg',
        'stories' => [
            ['image' => '../../public/img/dumphileee.jpg', 'timestamp' => '30 menit']
        ],
        'has_story' => true
    ],
    [
        'username' => 'arinassjj', 
        'avatar' => '../../public/img/arin.jpg',
        'stories' => [
            ['image' => '../../public/img/arin.jpg', 'timestamp' => '6 jam']
        ],
        'has_story' => true
    ],
    [
        'username' => 'wijaayakusuma', 
        'avatar' => '../../public/img/jaya.jpg',
        'stories' => [
            ['image' => '../../public/img/jaya.jpg', 'timestamp' => '8 jam'],
            ['image' => '../../public/img/jaya.jpg', 'timestamp' => '10 jam']
        ],
        'has_story' => true
    ],
    [
        'username' => 'my2ndpagee_', 
        'avatar' => '../../public/img/nina.jpg',
        'stories' => [
            ['image' => '../../public/img/nina.jpg', 'timestamp' => '12 jam']
        ],
        'has_story' => true
    ]
];

$suggestions = [
    ['username' => 'houseoffchilll', 'avatar' => '../../public/img/houseofchill.jpg','mutual' => 'Disarankan untuk Anda'],
    ['username' => 'aliviaa_putrii', 'avatar' => '../../public/img/lipia.jpg', 'mutual' => 'Disarankan untuk Anda'],
    ['username' => 'odyssmt_', 'avatar' => '../../public/img/ody.jpg', 'mutual' => 'Disarankan untuk Anda'],
    ['username' => 'oktaviatamd_', 'avatar' => '../../public/img/manda.jpg', 'mutual' => 'Diikuti oleh mamanx_x'],
    ['username' => 'whysetia_', 'avatar' => '../../public/img/wahyu.jpg', 'mutual' => 'Diikuti oleh fajridn_']
];

function renderHighlightsSection($stories) {
    ?>
    <div class="highlights-section">
        <div class="highlights-container">
            <?php foreach ($stories as $index => $story): ?>
                <div class="highlight-item" data-story-index="<?= $index ?>">
                    <?php if (isset($story['is_current_user']) && $story['is_current_user']): ?>
                        <!-- Add Story Button for Current User -->
                        <div class="story-ring add-story" onclick="openAddStory()">
                            <img src="<?= htmlspecialchars($story['avatar']) ?>" alt="<?= htmlspecialchars($story['username']) ?>" class="highlight-avatar">
                            <div class="add-story-plus">+</div>
                        </div>
                        <span class="highlight-username">Story Anda</span>
                    <?php else: ?>
                        <div class="story-ring <?= $story['has_story'] ? 'has-story' : '' ?>" onclick="openStory(<?= $index ?>)">
                            <img src="<?= htmlspecialchars($story['avatar']) ?>" alt="<?= htmlspecialchars($story['username']) ?>" class="highlight-avatar">
                        </div>
                        <span class="highlight-username"><?= htmlspecialchars($story['username']) ?></span>
                    <?php endif; ?>
                </div>
            <?php endforeach; ?>
        </div>
    </div>

    <!-- Story Modal -->
    <div id="storyModal" class="story-modal">
        <div class="story-container">
            <div class="story-header">
                <div class="story-progress-bars">
                    <!-- Progress bars will be generated by JavaScript -->
                </div>
                <div class="story-user-info">
                    <img id="storyUserAvatar" src="" alt="" class="story-user-avatar">
                    <span id="storyUsername"></span>
                    <span id="storyTimestamp" class="story-timestamp"></span>
                </div>
                <button class="story-close" onclick="closeStory()">×</button>
            </div>
            
            <div class="story-content">
                <img id="storyImage" src="" alt="Story">
                <div class="story-navigation">
                    <div class="story-prev" onclick="previousStory()"></div>
                    <div class="story-next" onclick="nextStory()"></div>
                </div>
            </div>
            
            <div class="story-actions">
                <input type="text" placeholder="Kirim pesan" class="story-message-input">
                <button class="story-heart">❤</button>
                <button class="story-share">📤</button>
            </div>
        </div>
    </div>

    <!-- Add Story Modal -->
    <div id="addStoryModal" class="story-modal add-story-modal">
        <div class="add-story-container">
            <div class="add-story-header">
                <h3>Buat story</h3>
                <button class="story-close" onclick="closeAddStory()">×</button>
            </div>
            
            <!-- Photo Upload Area -->
            <div class="photo-upload-area" id="photoUploadArea">
                <div class="upload-placeholder">
                    <div class="upload-icon">📷</div>
                    <h3>Pilih foto untuk story</h3>
                    <p>Klik untuk memilih foto atau drag & drop</p>
                    <input type="file" id="storyPhotoInput" accept="image/*" style="display: none;">
                    <button class="upload-btn" onclick="document.getElementById('storyPhotoInput').click()">
                        Pilih Foto
                    </button>
                </div>
            </div>

            <!-- Story Preview -->
            <div class="story-preview" id="storyPreview" style="display: none;">
                <!-- Story Tools Header -->
                <div class="story-tools-header">
                    <button class="story-tool-btn" onclick="closeAddStory()">✕</button>
                    <button class="story-tool-btn" onclick="toggleBoomerang()">∞</button>
                    <button class="story-tool-btn" onclick="addText()" id="textToolBtn">Aa</button>
                    <button class="story-tool-btn" onclick="addSticker()">😊</button>
                    <button class="story-tool-btn" onclick="addMusic()">♪</button>
                    <button class="story-tool-btn" onclick="addSparkles()">✨</button>
                    <button class="story-tool-btn more-tools" onclick="showMoreTools()">⋯</button>
                </div>
                
                <div class="preview-content">
                    <img id="previewImage" src="" alt="Story Preview">
                    <!-- Draggable text elements will be added here -->
                    <div class="draggable-elements" id="draggableElements"></div>
                </div>
                
                <!-- Bottom Text Input -->
                <div class="story-text-input-bottom" id="storyTextInputBottom" style="display: none;">
                    <input type="text" id="storyTextInput" placeholder="Tambahkan keterangan..." maxlength="100">
                    <div class="text-style-options">
                        <button class="text-style-btn" onclick="changeTextStyle('classic')" data-style="classic">A</button>
                        <button class="text-style-btn" onclick="changeTextStyle('modern')" data-style="modern">𝗔</button>
                        <button class="text-style-btn" onclick="changeTextStyle('neon')" data-style="neon">𝔸</button>
                        <button class="text-style-btn" onclick="changeTextStyle('typewriter')" data-style="typewriter">𝙰</button>
                    </div>
                    <div class="text-color-options">
                        <div class="color-picker">
                            <button class="color-btn" data-color="white" style="background: white; border: 2px solid #333;"></button>
                            <button class="color-btn" data-color="#ff3040" style="background: #ff3040;"></button>
                            <button class="color-btn" data-color="#0095f6" style="background: #0095f6;"></button>
                            <button class="color-btn" data-color="#00d924" style="background: #00d924;"></button>
                            <button class="color-btn" data-color="#ffcc00" style="background: #ffcc00;"></button>
                            <button class="color-btn" data-color="#ff6b35" style="background: #ff6b35;"></button>
                            <button class="color-btn" data-color="#8a2be2" style="background: #8a2be2;"></button>
                            <button class="color-btn" data-color="#ff1493" style="background: #ff1493;"></button>
                        </div>
                    </div>
                    <button class="done-text-btn" onclick="addTextToStory()">Selesai</button>
                </div>
                
                <!-- Bottom Story Actions -->
                <div class="story-bottom-actions">
                    <div class="story-bottom-left">
                        <button class="bottom-action-btn" onclick="saveStoryDraft()">
                            <span class="btn-icon">💾</span>
                        </button>
                        <button class="bottom-action-btn" onclick="toggleStoryPrivacy()" id="privacyBtn">
                            <span class="btn-icon">👁</span>
                        </button>
                    </div>
                    
                    <div class="story-bottom-center">
                        <div class="share-options">
                            <div class="share-option" onclick="shareToStory('story')">
                                <div class="share-avatar">
                                    <img src="../../public/img/gambar3.jpg" alt="Your Story">
                                </div>
                                <span>Cerita Anda</span>
                            </div>
                            <div class="share-option" onclick="shareToStory('close_friends')">
                                <div class="share-avatar close-friends">
                                    <img src="../../public/img/gambar3.jpg" alt="Close Friends">
                                    <div class="close-friends-badge">⭐</div>
                                </div>
                                <span>Teman Dekat</span>
                            </div>
                        </div>
                    </div>
                    
                    <div class="story-bottom-right">
                        <button class="send-story-btn" onclick="showSendStoryModal()">
                            <span class="send-icon">→</span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Story Success Modal -->
    <div id="storySuccessModal" class="story-modal">
        <div class="success-container">
            <div class="success-content">
                <div class="success-icon">✅</div>
                <h3>Story berhasil dibagikan!</h3>
                <p>Story Anda sekarang dapat dilihat oleh pengikut selama 24 jam</p>
                <button class="success-btn" onclick="closeSuccessModal()">OK</button>
            </div>
        </div>
    </div>
    <?php
}

function renderFeedSection($posts, $stories) {
    ?>
    <div class="section" id="feed">
        <div class="feed-section">
            <!-- Feed Posts -->
            <?php if (!empty($posts)): ?>
                <?php foreach ($posts as $post): ?>
                    <div class="feed-post">
                        <!-- Post Header -->
                        <div class="post-header">
                            <img src="<?= htmlspecialchars($post['avatar'] ?? 'public/img/gambar3.jpg') ?>" alt="<?= htmlspecialchars($post['username']) ?>" class="post-avatar">
                            <a href="#" class="post-username"><?= htmlspecialchars($post['username']) ?></a>
                            <span class="post-time"><?= date('j M', strtotime($post['created_at'] ?? 'now')) ?></span>
                            <button class="post-options">⋯</button>
                        </div>
                        
                        <!-- Post Images (multiple) -->
                        <?php if (!empty($post['image'])): ?>
                            <div class="post-images">
                 <img src="<?= '/public/img/' . htmlspecialchars($post['image']) ?>" alt="Post Image">
                                
                            </div>
                        <?php else: ?>
                            <div class="post-placeholder">
                                <i class="fas fa-camera fa-2x"></i>
                            </div>
                        <?php endif; ?>
                        
                        <!-- Post Actions -->
                        <div class="post-actions">
                            <form action="../../models/Like.php" method="POST">
                            <input type="hidden" name="post_id" value="<?= $post['id_post'] ?>">
                                <input type="hidden" name="type" value="post">
                                <button type="submit" class="post-action heart-button <?= $post['is_liked'] ? 'liked' : '' ?>"></button>
                            </form>
                            <button class="post-action">💬</button>
                            <button class="post-action">📤</button>
                            <button class="post-action">🔖</button>
                        </div>
                        
                        <!-- Post Likes & Caption -->
                        <div class="post-content-text">
                            <div class="post-likes">42 suka</div>
                            <div class="post-caption">
                                <span class="username"><?= htmlspecialchars($post['username']) ?></span>
                                <?= htmlspecialchars($post['caption'] ?? '') ?>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php else: ?>
                <div class="no-posts">
                    <i class="fas fa-camera fa-3x mb-3"></i>
                    <h3>Belum ada postingan di feed</h3>
                    <p>Mulai berbagi momen Anda atau ikuti akun lain</p>
                </div>
            <?php endif; ?>
        </div>
    </div>
    <?php
}

function renderRightSidebar($suggestions) {
    ?>
    <div class="sidebar-right">
        <div class="profile-switch">
            <div class="profile-info">
                <form id="formProfilePic" enctype="multipart/form-data">
                    <label for="profilePicInput">
                        <img id="profileAvatar" src="../../public/img/gambar1.jpg" alt="_dwiirhma" class="profile-avatar">
                    </label>
                    <input type="file" id="profilePicInput" name="profile_pic" accept="image/*" style="display:none;">
                </form>
                <div class="profile-details">
                    <h6 class="profile-username">_dwiirhma</h6>
                </div>
            </div>
            <button class="switch-btn">Alihkan</button>
        </div>

        <div class="suggestions">
            <div class="suggestions-header">
                <h3 class="suggestions-title">Disarankan untuk Anda</h3>
                <a href="#" class="see-all">Lihat Semua</a>
            </div>
            
            <?php foreach($suggestions as $suggestion): ?>
            <div class="suggestion-item">
                <div class="suggestion-info">
                    <img src="<?php echo $suggestion['avatar']; ?>" alt="<?php echo $suggestion['username']; ?>" class="suggestion-avatar">
                    <div class="suggestion-details">
                        <h5><?php echo $suggestion['username']; ?></h5>
                        <p><?php echo $suggestion['mutual']; ?></p>
                    </div>
                </div>
                <button class="follow-btn">Ikuti</button>
            </div>
            <?php endforeach; ?>
        </div>

        <div class="footer">
            <div class="footer-links">
                <a href="#">Tentang</a> • 
                <a href="#">Bantuan</a> • 
                <a href="#">Pers</a> • 
                <a href="#">API</a> • 
                <a href="#">Pekerjaan</a> • 
                <a href="#">Privasi</a> • 
                <a href="#">Ketentuan</a> • 
                <a href="#">Lokasi</a> • 
                <a href="#">Bahasa</a> • 
                <a href="#">Verifikasi Meta</a>
            </div>
            <p>© 2025 INSTAGRAM FROM META</p>
        </div>
    </div>
    <?php
}
?>
 
    <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Instagram Feed</title>
    <style>
        /* General Reset */
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
        }

        body {
            background: #000000;
            color: #ffffff;
        }

        .instagram-container {
            display: flex;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
        }

        /* Main Content */
        .main-content {
            flex: 2;
            margin-right: 30px;
        }

        .highlights-section {
            margin-bottom: 20px;
        }

         .error-message, .message {
        padding: 10px;
        margin: 10px 0;
        border-radius: 5px;
    }
    .error-message {
        background-color: #f8d7da;
        color: #721c24;
    }
    .message {
        background-color: #d4edda;
        color: #155724;
    }
    .heart-button.liked::after {
        content: '❤️';
        color: red;
    }
    .heart-button::after {
        content: '🤍';
    }


        .highlights-title {
            font-weight: 600;
            color: #ffffff;
            margin-bottom: 10px;
        }

        .highlights-container {
            display: flex;
            overflow-x: auto;
            gap: 10px;
            padding-bottom: 10px;
            -webkit-overflow-scrolling: touch;
        }

        .highlight-item {
            display: flex;
            flex-direction: column;
            align-items: center;
            min-width: 80px;
            text-align: center;
            cursor: pointer;
        }

        .story-ring {
            padding: 3px;
            border-radius: 50%;
            background: linear-gradient(45deg, #f09433 0%, #e6683c 25%, #dc2743 50%, #cc2366 75%, #bc1888 100%);
            transition: transform 0.2s;
        }

        .story-ring.has-story:hover {
            transform: scale(1.05);
        }

        .story-ring.viewed {
            background: #333333;
        }

        /* Add Story Styles */
        .story-ring.add-story {
            background: #333333;
            position: relative;
            border: 2px dashed #666;
        }

        .story-ring.add-story:hover {
            border-color: #999;
            transform: scale(1.05);
        }

        .add-story-plus {
            position: absolute;
            bottom: -2px;
            right: -2px;
            width: 24px;
            height: 24px;
            background: #0095f6;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            color: white;
            font-size: 16px;
            font-weight: bold;
            border: 2px solid #000;
        }

        /* Add Story Modal */
        .add-story-modal .story-container,
        .add-story-container {
            width: 480px;
            height: 600px;
            background: #262626;
            border-radius: 12px;
            overflow: hidden;
            position: relative;
        }

        .add-story-header {
            padding: 20px;
            border-bottom: 1px solid #333;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .add-story-header h3 {
            color: white;
            font-size: 18px;
            font-weight: 600;
        }

        .photo-upload-area {
            height: calc(100% - 80px);
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 40px;
        }

        .upload-placeholder {
            text-align: center;
            color: #ffffff;
        }

        .upload-icon {
            font-size: 60px;
            margin-bottom: 20px;
        }

        .upload-placeholder h3 {
            margin-bottom: 10px;
            font-size: 20px;
        }

        .upload-placeholder p {
            margin-bottom: 20px;
            color: #999;
        }

        .upload-btn {
            background: #0095f6;
            color: white;
            border: none;
            padding: 12px 24px;
            border-radius: 8px;
            font-weight: 600;
            cursor: pointer;
            font-size: 14px;
        }

        .upload-btn:hover {
            background: #0084d6;
        }

        /* Story Tools Header */
        .story-tools-header {
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            z-index: 10;
            padding: 15px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            background: linear-gradient(rgba(0,0,0,0.5), transparent);
        }

        .story-tool-btn {
            width: 44px;
            height: 44px;
            border-radius: 50%;
            background: rgba(0, 0, 0, 0.5);
            border: none;
            color: white;
            font-size: 18px;
            cursor: pointer;
            display: flex;
            align-items: center;
            justify-content: center;
            transition: all 0.2s;
        }

        .story-tool-btn:hover {
            background: rgba(0, 0, 0, 0.7);
            transform: scale(1.05);
        }

        .story-tool-btn.active {
            background: #0095f6;
        }

        /* Draggable Elements */
        .draggable-elements {
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            pointer-events: none;
        }

        .draggable-text {
            position: absolute;
            color: white;
            font-size: 24px;
            font-weight: bold;
            text-align: center;
            text-shadow: 2px 2px 4px rgba(0,0,0,0.8);
            cursor: move;
            pointer-events: all;
            user-select: none;
            padding: 10px;
            min-width: 100px;
            background: rgba(0, 0, 0, 0.3);
            border-radius: 8px;
            transform: translate(-50%, -50%);
        }

        .draggable-text.classic {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
        }

        .draggable-text.modern {
            font-family: 'Arial Black', sans-serif;
            font-weight: 900;
        }

        .draggable-text.neon {
            font-family: 'Impact', sans-serif;
            text-shadow: 0 0 10px currentColor, 2px 2px 4px rgba(0,0,0,0.8);
        }

        .draggable-text.typewriter {
            font-family: 'Courier New', monospace;
            font-weight: bold;
        }

        /* Bottom Text Input */
        .story-text-input-bottom {
            position: absolute;
            bottom: 0;
            left: 0;
            right: 0;
            background: linear-gradient(transparent, rgba(0, 0, 0, 0.8));
            padding: 20px;
            z-index: 9;
        }

        .story-text-input-bottom input {
            width: 100%;
            background: none;
            border: none;
            color: white;
            font-size: 18px;
            text-align: center;
            padding: 15px;
            margin-bottom: 15px;
            border-bottom: 1px solid rgba(255, 255, 255, 0.3);
        }

        .story-text-input-bottom input::placeholder {
            color: rgba(255, 255, 255, 0.7);
        }

        .text-style-options {
            display: flex;
            justify-content: center;
            gap: 15px;
            margin-bottom: 15px;
        }

        .text-style-btn {
            width: 40px;
            height: 40px;
            border-radius: 8px;
            background: rgba(255, 255, 255, 0.2);
            border: none;
            color: white;
            font-size: 18px;
            cursor: pointer;
            transition: all 0.2s;
        }

        .text-style-btn:hover,
        .text-style-btn.active {
            background: #0095f6;
            transform: scale(1.05);
        }

        .text-color-options {
            margin-bottom: 15px;
        }

        .color-picker {
            display: flex;
            justify-content: center;
            gap: 10px;
            flex-wrap: wrap;
        }

        .color-btn {
            width: 30px;
            height: 30px;
            border-radius: 50%;
            border: 2px solid rgba(255, 255, 255, 0.3);
            cursor: pointer;
            transition: all 0.2s;
        }

        .color-btn:hover,
        .color-btn.active {
            transform: scale(1.2);
            border-color: white;
        }

        .done-text-btn {
            width: 100%;
            background: #0095f6;
            color: white;
            border: none;
            padding: 12px;
            border-radius: 8px;
            font-weight: 600;
            cursor: pointer;
            font-size: 16px;
        }

        /* Bottom Story Actions */
        .story-bottom-actions {
            position: absolute;
            bottom: 0;
            left: 0;
            right: 0;
            padding: 20px;
            display: flex;
            align-items: end;
            justify-content: space-between;
            background: linear-gradient(transparent, rgba(0, 0, 0, 0.6));
            z-index: 8;
        }

        .story-bottom-left,
        .story-bottom-right {
            display: flex;
            flex-direction: column;
            gap: 15px;
        }

        .bottom-action-btn {
            width: 44px;
            height: 44px;
            border-radius: 50%;
            background: rgba(0, 0, 0, 0.5);
            border: none;
            color: white;
            font-size: 20px;
            cursor: pointer;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .send-story-btn {
            width: 44px;
            height: 44px;
            border-radius: 50%;
            background: #0095f6;
            border: none;
            color: white;
            font-size: 20px;
            cursor: pointer;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        /* Share Options */
        .story-bottom-center {
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .share-options {
            display: flex;
            gap: 20px;
        }

        .share-option {
            display: flex;
            flex-direction: column;
            align-items: center;
            cursor: pointer;
            transition: transform 0.2s;
        }

        .share-option:hover {
            transform: scale(1.05);
        }

        .share-avatar {
            width: 60px;
            height: 60px;
            position: relative;
            margin-bottom: 8px;
        }

        .share-avatar img {
            width: 100%;
            height: 100%;
            border-radius: 50%;
            object-fit: cover;
            border: 3px solid white;
        }

        .share-avatar.close-friends img {
            border-color: #00d924;
        }

        .close-friends-badge {
            position: absolute;
            bottom: -2px;
            right: -2px;
            width: 20px;
            height: 20px;
            background: #00d924;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 12px;
            border: 2px solid black;
        }

        .share-option span {
            color: white;
            font-size: 12px;
            text-align: center;
            font-weight: 500;
        }

        .preview-content {
            width: 100%;
            height: 100%;
            display: flex;
            align-items: center;
            justify-content: center;
            background: #000;
            position: relative;
        }

        .preview-content img {
            max-width: 100%;
            max-height: 100%;
            object-fit: contain;
        }

        /* Success Modal */
        .success-container {
            width: 400px;
            background: #262626;
            border-radius: 12px;
            padding: 40px;
            text-align: center;
        }

        .success-icon {
            font-size: 60px;
            margin-bottom: 20px;
        }

        .success-container h3 {
            color: white;
            margin-bottom: 10px;
            font-size: 18px;
        }

        .success-container p {
            color: #999;
            margin-bottom: 20px;
            line-height: 1.5;
        }

        .success-btn {
            background: #0095f6;
            color: white;
            border: none;
            padding: 12px 24px;
            border-radius: 8px;
            font-weight: 600;
            cursor: pointer;
            font-size: 14px;
            width: 100%;
        }

        .success-btn:hover {
            background: #0084d6;
        }

        /* Drag and Drop Styles */
        .photo-upload-area.dragover {
            background: rgba(0, 149, 246, 0.1);
            border: 2px dashed #0095f6;
        }

        .highlight-avatar {
            width: 72px;
            height: 72px;
            border-radius: 50%;
            object-fit: cover;
            border: 2px solid #000000;
            cursor: pointer;
        }

        .highlight-username {
            font-size: 12px;
            color: #ffffff;
            margin-top: 6px;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
            max-width: 80px;
        }

        /* Story Modal Styles */
        .story-modal {
            display: none;
            position: fixed;
            top: 0;
            left: 0;
            width: 100vw;
            height: 100vh;
            background: rgba(0, 0, 0, 0.9);
            z-index: 9999;
            justify-content: center;
            align-items: center;
        }

        .story-modal.active {
            display: flex;
        }

        .story-container {
            width: 375px;
            height: 667px;
            background: #000;
            border-radius: 12px;
            overflow: hidden;
            position: relative;
        }

        .story-header {
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            z-index: 2;
            padding: 15px;
        }

        .story-progress-bars {
            display: flex;
            gap: 2px;
            margin-bottom: 15px;
        }

        .story-progress-bar {
            flex: 1;
            height: 2px;
            background: rgba(255, 255, 255, 0.3);
            border-radius: 1px;
            overflow: hidden;
        }

        .story-progress-fill {
            height: 100%;
            background: white;
            width: 0%;
            transition: width 0.1s ease;
        }

        .story-user-info {
            display: flex;
            align-items: center;
            gap: 10px;
        }

        .story-user-avatar {
            width: 32px;
            height: 32px;
            border-radius: 50%;
            object-fit: cover;
        }

        .story-timestamp {
            color: rgba(255, 255, 255, 0.7);
            font-size: 14px;
            margin-left: 5px;
        }

        .story-close {
            position: absolute;
            top: 15px;
            right: 15px;
            background: none;
            border: none;
            color: white;
            font-size: 24px;
            cursor: pointer;
            z-index: 3;
        }

        .story-content {
            width: 100%;
            height: 100%;
            position: relative;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .story-content img {
            width: 100%;
            height: 100%;
            object-fit: cover;
        }

        .story-navigation {
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            display: flex;
        }

        .story-prev,
        .story-next {
            flex: 1;
            cursor: pointer;
            z-index: 1;
        }

        .story-actions {
            position: absolute;
            bottom: 0;
            left: 0;
            right: 0;
            padding: 15px;
            display: flex;
            align-items: center;
            gap: 10px;
            background: linear-gradient(transparent, rgba(0, 0, 0, 0.3));
        }

        .story-message-input {
            flex: 1;
            background: none;
            border: 1px solid rgba(255, 255, 255, 0.3);
            border-radius: 20px;
            padding: 8px 15px;
            color: white;
            font-size: 14px;
        }

        .story-message-input::placeholder {
            color: rgba(255, 255, 255, 0.7);
        }

        .story-heart,
        .story-share {
            background: none;
            border: none;
            color: white;
            font-size: 20px;
            cursor: pointer;
        }

        .feed-section {
            max-width: 614px;
            margin: 0 auto;
        }

        .feed-post {
            max-width: 500px;
            margin: 30px auto;
            border: 1px solid #333333;
            border-radius: 8px;
            background: #000000;
        }

        .post-header {
            display: flex;
            align-items: center;
            padding: 12px;
        }

        .post-avatar {
            width: 32px;
            height: 32px;
            border-radius: 50%;
            object-fit: cover;
            margin-right: 12px;
        }

        .post-username {
            font-weight: 600;
            color: #ffffff;
            text-decoration: none;
        }

        .post-time {
            color: #ffffff;
            margin-left: auto;
        }

        .post-options {
            background: none;
            border: none;
            color: #ffffff;
            font-size: 20px;
            margin-left: 8px;
            cursor: pointer;
        }

        .post-images img {
            width: 100%;
            max-height: 500px;
            object-fit: cover;
            display: block;
        }

        .post-placeholder {
            width: 100%;
            height: 300px;
            background: #1a1a1a;
            display: flex;
            align-items: center;
            justify-content: center;
            color: #ffffff;
        }

        .post-actions {
            display: flex;
            align-items: center;
            padding: 8px 12px;
        }

        .post-action {
            background: none;
            border: none;
            font-size: 22px;
            margin-right: 8px;
            cursor: pointer;
        }

        .post-action:last-child {
            margin-left: auto;
            margin-right: 0;
        }

        .post-content-text {
            padding: 0 12px 12px;
        }

        .post-likes {
            font-weight: 600;
            margin-bottom: 4px;
            color: #ffffff;
        }

        .post-caption .username {
            font-weight: 600;
            color: #ffffff;
        }

        .post-caption {
            color: #ffffff;
        }

        .no-posts {
            text-align: center;
            padding: 60px 0;
            color: #ffffff;
        }

        .no-posts i {
            margin-bottom: 16px;
        }

        /* Sidebar */
        .sidebar-right {
            flex: 1;
            max-width: 350px;
            position: sticky;
            top: 20px;
            align-self: flex-start;
        }

        .profile-switch {
            display: flex;
            align-items: center;
            justify-content: space-between;
            margin-bottom: 20px;
            gap: 24px;
        }

        .profile-info {
            display: flex;
            align-items: center;
        }

        .profile-avatar {
            width: 56px;
            height: 56px;
            border-radius: 50%;
            object-fit: cover;
            margin-right: 12px;
        }

        .profile-details h4 {
            font-weight: 600;
            color: #ffffff;
        }

        .profile-details p {
            color: #ffffff;
            font-size: 14px;
        }

        .switch-btn {
            background: none;
            border: none;
            color: #0095f6;
            font-weight: 600;
            cursor: pointer;
            font-size: 15px;
            margin-left: 12px;
        }

        .suggestions-header {
            display: flex;
            justify-content: space-between;
            margin-bottom: 12px;
        }

        .suggestions-title {
            font-weight: 600;
            color: #ffffff;
            font-size: 11px; 
            letter-spacing: 0.2px;
        }

        .see-all {
            font-weight: 600;
            color: #ffffff;
            text-decoration: none;
            font-size: 14px;
        }

        .suggestion-item {
            display: flex;
            align-items: center;
            justify-content: space-between;
            margin-bottom: 12px;
        }

        .suggestion-info {
            display: flex;
            align-items: center;
        }

        .suggestion-avatar {
            width: 32px;
            height: 32px;
            border-radius: 50%;
            object-fit: cover;
            margin-right: 12px;
        }

        .suggestion-details h5 {
            font-weight: 600;
            color: #ffffff;
        }

        .suggestion-details p {
            color: #ffffff;
            font-size: 12px;
        }

        .follow-btn {
            background: none;
            border: none;
            color: #ffffff;
            font-weight: 600;
            cursor: pointer;
        }

        .footer {
            margin-top: 20px;
            color: #ffffff;
            font-size: 12px;
        }

        .footer-links a {
            color: #ffffff;
            text-decoration: none;
            margin-right: 4px;
        }

        .footer p {
            margin-top: 8px;
        }

        /* Responsive Design */
        @media (max-width: 768px) {
            .instagram-container {
                flex-direction: column;
                padding: 10px;
            }

            .main-content {
                margin-right: 0;
            }

            .sidebar-right {
                max-width: 100%;
                position: static;
                top: 0;
            }

            .highlights-container {
                flex-wrap: nowrap;
                overflow-x: auto;
            }

            .story-container {
                width: 100vw;
                height: 100vh;
                border-radius: 0;
            }

            .add-story-container {
                width: 100vw;
                height: 100vh;
                border-radius: 0;
            }

            .success-container {
                width: 90vw;
                max-width: 400px;
            }
        }
    </style>
</head>
<body>
    <div class="instagram-container">
        <!-- Main Content -->
        <main class="main-content">
            <?php renderHighlightsSection($stories); ?>
            <?php renderFeedSection($posts, $stories); ?>
        </main>
        
        <?php renderRightSidebar($suggestions); ?>
    </div>

<<<<<<< HEAD
    <script>
        // Story data from PHP
        const storiesData = <?= json_encode($stories) ?>;
        let currentUserIndex = 0;
        let currentStoryIndex = 0;
        let storyTimer;
        let progressTimer;
        let currentTextColor = 'white';
        let currentTextSize = 18;
        let currentTextStyle = 'classic';
        let draggedElement = null;
        let textElements = [];
        let storyPrivacy = 'public'; // public or close_friends

        // Story Tools Functions
        function toggleBoomerang() {
            // Toggle boomerang effect (placeholder)
            const btn = event.target;
            btn.classList.toggle('active');
        }

        function addText() {
            const textInput = document.getElementById('storyTextInputBottom');
            const isVisible = textInput.style.display !== 'none';
            
            if (isVisible) {
                textInput.style.display = 'none';
                document.getElementById('textToolBtn').classList.remove('active');
            } else {
                textInput.style.display = 'block';
                document.getElementById('textToolBtn').classList.add('active');
                document.getElementById('storyTextInput').focus();
            }
        }

        function addSticker() {
            // Add sticker functionality (placeholder)
            alert('Fitur sticker akan segera hadir!');
        }

        function addMusic() {
            // Add music functionality (placeholder)
            alert('Fitur musik akan segera hadir!');
        }

        function addSparkles() {
            // Add sparkles effect (placeholder)
            alert('Fitur efek akan segera hadir!');
        }

        function showMoreTools() {
            // Show more tools (placeholder)
            alert('Lebih banyak tools akan segera hadir!');
        }

        function changeTextStyle(style) {
            currentTextStyle = style;
            
            // Update active button
            document.querySelectorAll('.text-style-btn').forEach(btn => {
                btn.classList.remove('active');
            });
            document.querySelector(`[data-style="${style}"]`).classList.add('active');
        }

        function addTextToStory() {
            const textInput = document.getElementById('storyTextInput');
            const text = textInput.value.trim();
            
            if (text) {
                createDraggableText(text);
                textInput.value = '';
                document.getElementById('storyTextInputBottom').style.display = 'none';
                document.getElementById('textToolBtn').classList.remove('active');
            }
        }

        function createDraggableText(text) {
            const textElement = document.createElement('div');
            textElement.className = `draggable-text ${currentTextStyle}`;
            textElement.textContent = text;
            textElement.style.color = currentTextColor;
            textElement.style.fontSize = currentTextSize + 'px';
            textElement.style.left = '50%';
            textElement.style.top = '50%';
            
            // Make draggable
            textElement.addEventListener('mousedown', startDragging);
            textElement.addEventListener('touchstart', startDragging);
            
            // Double click to edit
            textElement.addEventListener('dblclick', editText);
            
            document.getElementById('draggableElements').appendChild(textElement);
            textElements.push(textElement);
        }

        function startDragging(e) {
            draggedElement = e.target;
            const rect = draggedElement.getBoundingClientRect();
            const containerRect = document.querySelector('.preview-content').getBoundingClientRect();
            
            const startX = e.type === 'mousedown' ? e.clientX : e.touches[0].clientX;
            const startY = e.type === 'mousedown' ? e.clientY : e.touches[0].clientY;
            
            function drag(e) {
                const currentX = e.type === 'mousemove' ? e.clientX : e.touches[0].clientX;
                const currentY = e.type === 'mousemove' ? e.clientY : e.touches[0].clientY;
                
                const deltaX = currentX - startX;
                const deltaY = currentY - startY;
                
                const newLeft = ((rect.left + deltaX - containerRect.left) / containerRect.width) * 100;
                const newTop = ((rect.top + deltaY - containerRect.top) / containerRect.height) * 100;
                
                draggedElement.style.left = Math.max(10, Math.min(90, newLeft)) + '%';
                draggedElement.style.top = Math.max(10, Math.min(90, newTop)) + '%';
            }
            
            function stopDragging() {
                document.removeEventListener('mousemove', drag);
                document.removeEventListener('mouseup', stopDragging);
                document.removeEventListener('touchmove', drag);
                document.removeEventListener('touchend', stopDragging);
                draggedElement = null;
            }
            
            document.addEventListener('mousemove', drag);
            document.addEventListener('mouseup', stopDragging);
            document.addEventListener('touchmove', drag);
            document.addEventListener('touchend', stopDragging);
        }

        function editText(e) {
            const element = e.target;
            const currentText = element.textContent;
            const newText = prompt('Edit teks:', currentText);
            if (newText !== null && newText.trim()) {
                element.textContent = newText.trim();
            }
        }

        // Color picker functionality
=======
   

    <!-- <script src="modules/home/instagram.js"></script> -->
</div>
     <script>

        // Membungkus semua kode di dalam DOMContentLoaded untuk memastikan semua elemen HTML siap
>>>>>>> 6373fe487644ce55e445e4adc7d05694d4ebb5fb
        document.addEventListener('DOMContentLoaded', function() {
            // Story data from PHP
            const storiesData = <?= json_encode($stories) ?>;
            let currentUserIndex = 0;
            let currentStoryIndex = 0;
            let storyTimer;
            let progressTimer;
            let currentTextColor = 'white';
            let currentTextSize = 18;
            let currentTextStyle = 'classic';
            let draggedElement = null;
            let textElements = [];
            let storyPrivacy = 'public'; // public or close_friends

            // Story Tools Functions
            window.toggleBoomerang = function() {
                // Toggle boomerang effect (placeholder)
                const btn = event.target;
                btn.classList.toggle('active');
            }

            window.addText = function() {
                const textInput = document.getElementById('storyTextInputBottom');
                const isVisible = textInput.style.display !== 'none';
                
                if (isVisible) {
                    textInput.style.display = 'none';
                    document.getElementById('textToolBtn').classList.remove('active');
                } else {
                    textInput.style.display = 'block';
                    document.getElementById('textToolBtn').classList.add('active');
                    document.getElementById('storyTextInput').focus();
                }
            }

            window.addSticker = function() {
                alert('Fitur sticker akan segera hadir!');
            }

            window.addMusic = function() {
                alert('Fitur musik akan segera hadir!');
            }

            window.addSparkles = function() {
                alert('Fitur efek akan segera hadir!');
            }

            window.showMoreTools = function() {
                alert('Lebih banyak tools akan segera hadir!');
            }

            window.changeTextStyle = function(style) {
                currentTextStyle = style;
                
                // Update active button
                document.querySelectorAll('.text-style-btn').forEach(btn => {
                    btn.classList.remove('active');
                });
                // PERBAIKAN: Menggunakan template literal untuk querySelector yang benar
                document.querySelector(`[data-style="${style}"]`).classList.add('active');
            }

            window.addTextToStory = function() {
                const textInput = document.getElementById('storyTextInput');
                const text = textInput.value.trim();
                
                if (text) {
                    createDraggableText(text);
                    textInput.value = '';
                    document.getElementById('storyTextInputBottom').style.display = 'none';
                    document.getElementById('textToolBtn').classList.remove('active');
                }
            }

            function createDraggableText(text) {
                const textElement = document.createElement('div');
                // PERBAIKAN: Menggunakan template literal untuk className
                textElement.className = `draggable-text ${currentTextStyle}`;
                textElement.textContent = text;
                textElement.style.color = currentTextColor;
                textElement.style.fontSize = currentTextSize + 'px';
                textElement.style.left = '50%';
                textElement.style.top = '50%';
                
                textElement.addEventListener('mousedown', startDragging);
                textElement.addEventListener('touchstart', startDragging);
                textElement.addEventListener('dblclick', editText);
                
                document.getElementById('draggableElements').appendChild(textElement);
                textElements.push(textElement);
            }

            function startDragging(e) {
                draggedElement = e.target;
                const rect = draggedElement.getBoundingClientRect();
                const containerRect = document.querySelector('.preview-content').getBoundingClientRect();
                
                const startX = e.type === 'mousedown' ? e.clientX : e.touches[0].clientX;
                const startY = e.type === 'mousedown' ? e.clientY : e.touches[0].clientY;
                
                function drag(ev) {
                    const currentX = ev.type === 'mousemove' ? ev.clientX : ev.touches[0].clientX;
                    const currentY = ev.type === 'mousemove' ? ev.clientY : ev.touches[0].clientY;
                    
                    const deltaX = currentX - startX;
                    const deltaY = currentY - startY;
                    
                    const newLeft = ((rect.left + deltaX - containerRect.left) / containerRect.width) * 100;
                    const newTop = ((rect.top + deltaY - containerRect.top) / containerRect.height) * 100;
                    
                    draggedElement.style.left = Math.max(10, Math.min(90, newLeft)) + '%';
                    draggedElement.style.top = Math.max(10, Math.min(90, newTop)) + '%';
                }
                
                function stopDragging() {
                    document.removeEventListener('mousemove', drag);
                    document.removeEventListener('mouseup', stopDragging);
                    document.removeEventListener('touchmove', drag);
                    document.removeEventListener('touchend', stopDragging);
                    draggedElement = null;
                }
                
                document.addEventListener('mousemove', drag);
                document.addEventListener('mouseup', stopDragging);
                document.addEventListener('touchmove', drag);
                document.addEventListener('touchend', stopDragging);
            }

            function editText(e) {
                const element = e.target;
                const currentText = element.textContent;
                const newText = prompt('Edit teks:', currentText);
                if (newText !== null && newText.trim()) {
                    element.textContent = newText.trim();
                }
            }

            document.querySelectorAll('.color-btn').forEach(btn => {
                btn.addEventListener('click', function() {
                    currentTextColor = this.dataset.color;
                    document.querySelectorAll('.color-btn').forEach(b => b.classList.remove('active'));
                    this.classList.add('active');
                });
            });

<<<<<<< HEAD
        function saveStoryDraft() {
            // Save story as draft (placeholder)
            alert('Story disimpan sebagai draft!');
        }

        function toggleStoryPrivacy() {
            const btn = document.getElementById('privacyBtn');
            if (storyPrivacy === 'public') {
                storyPrivacy = 'close_friends';
                btn.innerHTML = '<span class="btn-icon">👥</span>';
                btn.style.background = '#00d924';
            } else {
                storyPrivacy = 'public';
                btn.innerHTML = '<span class="btn-icon">👁️</span>';
                btn.style.background = 'rgba(0, 0, 0, 0.5)';
            }
        }

        function shareToStory(type) {
            // Collect all text elements data
            const storyData = {
                image: document.getElementById('previewImage').src,
                textElements: textElements.map(el => ({
                    text: el.textContent,
                    left: el.style.left,
                    top: el.style.top,
                    color: el.style.color,
                    fontSize: el.style.fontSize,
                    className: el.className
                })),
                type: type
            };
            
            // Add to stories data
            const currentUser = storiesData[0];
            const newStory = {
                image: storyData.image,
                timestamp: 'Sekarang',
                textElements: storyData.textElements,
                type: type
            };
            
            if (!currentUser.stories) {
                currentUser.stories = [];
            }
            
            currentUser.stories.unshift(newStory);
            currentUser.has_story = true;
            
            // Update UI
            updateCurrentUserStoryRing();
            
            // Close modal and show success
            closeAddStory();
            showSuccessModal();
        }

        function showSendStoryModal() {
            alert('Fitur kirim story ke teman akan segera hadir!');
        }

        // Add Story Functions
        function openAddStory() {
            const modal = document.getElementById('addStoryModal');
            modal.classList.add('active');
            setupDragAndDrop();
        }

        function closeAddStory() {
            const modal = document.getElementById('addStoryModal');
            modal.classList.remove('active');
            
            // Reset form
            document.getElementById('photoUploadArea').style.display = 'flex';
            document.getElementById('storyPreview').style.display = 'none';
            document.getElementById('storyPhotoInput').value = '';
            document.getElementById('storyTextInputBottom').style.display = 'none';
            document.getElementById('textToolBtn').classList.remove('active');
            
            // Reset text elements
            textElements = [];
            document.getElementById('draggableElements').innerHTML = '';
            
            // Reset privacy
            storyPrivacy = 'public';
            const privacyBtn = document.getElementById('privacyBtn');
            if (privacyBtn) {
                privacyBtn.innerHTML = '<span class="btn-icon">👁️</span>';
                privacyBtn.style.background = 'rgba(0, 0, 0, 0.5)';
            }
        }

        function setupDragAndDrop() {
            const uploadArea = document.getElementById('photoUploadArea');
            
            ['dragenter', 'dragover', 'dragleave', 'drop'].forEach(eventName => {
                uploadArea.addEventListener(eventName, preventDefaults, false);
            });

            function preventDefaults(e) {
                e.preventDefault();
                e.stopPropagation();
=======
            window.saveStoryDraft = function() {
                alert('Story disimpan sebagai draft!');
>>>>>>> 6373fe487644ce55e445e4adc7d05694d4ebb5fb
            }

            window.toggleStoryPrivacy = function() {
                const btn = document.getElementById('privacyBtn');
                if (storyPrivacy === 'public') {
                    storyPrivacy = 'close_friends';
                    btn.innerHTML = '<span class="btn-icon">👥</span>';
                    btn.style.background = '#00d924';
                } else {
                    storyPrivacy = 'public';
                    btn.innerHTML = '<span class="btn-icon">👁</span>';
                    btn.style.background = 'rgba(0, 0, 0, 0.5)';
                }
            }

            window.shareToStory = function(type) {
                const storyData = {
                    image: document.getElementById('previewImage').src,
                    textElements: textElements.map(el => ({
                        text: el.textContent,
                        left: el.style.left,
                        top: el.style.top,
                        color: el.style.color,
                        fontSize: el.style.fontSize,
                        className: el.className
                    })),
                    type: type
                };
                
                const currentUser = storiesData[0];
                const newStory = {
                    image: storyData.image,
                    timestamp: 'Sekarang',
                    textElements: storyData.textElements,
                    type: type
                };
                
                if (!currentUser.stories) currentUser.stories = [];
                
                currentUser.stories.unshift(newStory);
                currentUser.has_story = true;
                
                updateCurrentUserStoryRing();
                closeAddStory();
                showSuccessModal();
            }

            window.showSendStoryModal = function() {
                alert('Fitur kirim story ke teman akan segera hadir!');
            }

            window.openAddStory = function() {
                document.getElementById('addStoryModal').classList.add('active');
                setupDragAndDrop();
            }

            window.closeAddStory = function() {
                const modal = document.getElementById('addStoryModal');
                modal.classList.remove('active');
                
                document.getElementById('photoUploadArea').style.display = 'flex';
                document.getElementById('storyPreview').style.display = 'none';
                document.getElementById('storyPhotoInput').value = '';
                document.getElementById('storyTextInputBottom').style.display = 'none';
                document.getElementById('textToolBtn').classList.remove('active');
                
                textElements = [];
                document.getElementById('draggableElements').innerHTML = '';
                
                storyPrivacy = 'public';
                const privacyBtn = document.getElementById('privacyBtn');
                if (privacyBtn) {
                    privacyBtn.innerHTML = '<span class="btn-icon">👁</span>';
                    privacyBtn.style.background = 'rgba(0, 0, 0, 0.5)';
                }
            }

<<<<<<< HEAD
        function showSuccessModal() {
            const modal = document.getElementById('storySuccessModal');
            modal.classList.add('active');
            
            // Auto close after 3 seconds
            setTimeout(() => {
                closeSuccessModal();
            }, 3000);
        }

        function closeSuccessModal() {
            const modal = document.getElementById('storySuccessModal');
            modal.classList.remove('active');
        }

        function openStory(userIndex) {
            currentUserIndex = userIndex;
            currentStoryIndex = 0;
            
            const modal = document.getElementById('storyModal');
            modal.classList.add('active');
            
            // Mark story as viewed
            const storyRing = document.querySelector(`[data-story-index="${userIndex}"] .story-ring`);
            if (storyRing) {
                storyRing.classList.add('viewed');
            }
            
            showStory();
            document.addEventListener('keydown', handleKeyPress);
        }

        function closeStory() {
            const modal = document.getElementById('storyModal');
            modal.classList.remove('active');
            
            clearTimeout(storyTimer);
            clearInterval(progressTimer);
            document.removeEventListener('keydown', handleKeyPress);
        }

        function showStory() {
            const user = storiesData[currentUserIndex];
            const story = user.stories[currentStoryIndex];
            
            // Update story content
            document.getElementById('storyUserAvatar').src = user.avatar;
            document.getElementById('storyUsername').textContent = user.username;
            document.getElementById('storyTimestamp').textContent = story.timestamp;
            document.getElementById('storyImage').src = story.image;
            
            // Add text overlay if story has text
            let textOverlay = document.querySelector('.story-text-display');
            if (textOverlay) {
                textOverlay.remove();
            }
            
            if (story.text && story.text.trim() !== '') {
                textOverlay = document.createElement('div');
                textOverlay.className = 'story-text-display';
                textOverlay.style.cssText = `
                    position: absolute;
                    bottom: 120px;
                    left: 20px;
                    right: 20px;
                    text-align: center;
                    font-size: ${story.textSize || 18}px;
                    color: ${story.textColor || 'white'};
                    font-weight: bold;
                    text-shadow: 2px 2px 4px rgba(0,0,0,0.8);
                    z-index: 3;
                    word-wrap: break-word;
                `;
                textOverlay.textContent = story.text;
                document.querySelector('.story-content').appendChild(textOverlay);
            }
            
            // Create progress bars
            createProgressBars();
            
            // Start story timer
            startStoryProgress();
        }

        function createProgressBars() {
            const user = storiesData[currentUserIndex];
            const progressContainer = document.querySelector('.story-progress-bars');
            progressContainer.innerHTML = '';
            
            user.stories.forEach((_, index) => {
                const progressBar = document.createElement('div');
                progressBar.className = 'story-progress-bar';
=======
            function setupDragAndDrop() {
                const uploadArea = document.getElementById('photoUploadArea');
>>>>>>> 6373fe487644ce55e445e4adc7d05694d4ebb5fb
                
                ['dragenter', 'dragover', 'dragleave', 'drop'].forEach(eventName => {
                    uploadArea.addEventListener(eventName, preventDefaults, false);
                });

                function preventDefaults(e) {
                    e.preventDefault();
                    e.stopPropagation();
                }

                ['dragenter', 'dragover'].forEach(eventName => {
                    uploadArea.addEventListener(eventName, () => uploadArea.classList.add('dragover'), false);
                });

                ['dragleave', 'drop'].forEach(eventName => {
                    uploadArea.addEventListener(eventName, () => uploadArea.classList.remove('dragover'), false);
                });

                uploadArea.addEventListener('drop', handleDrop, false);
            }

            function handleDrop(e) {
                const dt = e.dataTransfer;
                const files = dt.files;
                handleFiles(files);
            }

            function handleFiles(files) {
                if (files.length > 0 && files[0].type.startsWith('image/')) {
                    displayImagePreview(files[0]);
                }
            }

            function displayImagePreview(file) {
                const reader = new FileReader();
                reader.onload = function(e) {
                    document.getElementById('previewImage').src = e.target.result;
                    document.getElementById('photoUploadArea').style.display = 'none';
                    document.getElementById('storyPreview').style.display = 'block';
                    
                    textElements = [];
                    document.getElementById('draggableElements').innerHTML = '';
                };
                reader.readAsDataURL(file);
            }

            document.getElementById('storyPhotoInput').addEventListener('change', function(e) {
                if (e.target.files.length > 0) {
                    displayImagePreview(e.target.files[0]);
                }
            });

            function updateCurrentUserStoryRing() {
                const currentUserElement = document.querySelector('[data-story-index="0"] .story-ring');
                if (currentUserElement) {
                    currentUserElement.classList.remove('add-story');
                    currentUserElement.classList.add('has-story');
                    
                    const highlightItem = currentUserElement.parentElement;
                    highlightItem.setAttribute('onclick', 'openStory(0)');
                    
                    const usernameElement = highlightItem.querySelector('.highlight-username');
                    usernameElement.textContent = storiesData[0].username;
                    
                    const plusIcon = currentUserElement.querySelector('.add-story-plus');
                    if (plusIcon) plusIcon.remove();
                }
            }

            function showSuccessModal() {
                document.getElementById('storySuccessModal').classList.add('active');
                setTimeout(closeSuccessModal, 3000);
            }

            window.closeSuccessModal = function() {
                document.getElementById('storySuccessModal').classList.remove('active');
            }

            window.openStory = function(userIndex) {
                currentUserIndex = userIndex;
                currentStoryIndex = 0;
                
                document.getElementById('storyModal').classList.add('active');
                
                // PERBAIKAN: Menggunakan template literal untuk querySelector yang benar
                const storyRing = document.querySelector(`[data-story-index="${userIndex}"] .story-ring`);
                if (storyRing) {
                    storyRing.classList.add('viewed');
                }
                
                showStory();
                document.addEventListener('keydown', handleKeyPress);
            }

            window.closeStory = function() {
                document.getElementById('storyModal').classList.remove('active');
                clearTimeout(storyTimer);
                clearInterval(progressTimer);
                document.removeEventListener('keydown', handleKeyPress);
            }

            function showStory() {
                const user = storiesData[currentUserIndex];
                if (!user || !user.stories || user.stories.length === 0) {
                    closeStory();
                    return;
                }
                const story = user.stories[currentStoryIndex];
                
                document.getElementById('storyUserAvatar').src = user.avatar;
                document.getElementById('storyUsername').textContent = user.username;
                document.getElementById('storyTimestamp').textContent = story.timestamp;
                document.getElementById('storyImage').src = story.image;
                
                createProgressBars();
                startStoryProgress();
            }

            function createProgressBars() {
                const user = storiesData[currentUserIndex];
                const progressContainer = document.querySelector('.story-progress-bars');
                progressContainer.innerHTML = '';
                
                user.stories.forEach((_, index) => {
                    const progressBar = document.createElement('div');
                    progressBar.className = 'story-progress-bar';
                    const progressFill = document.createElement('div');
                    progressFill.className = 'story-progress-fill';
                    
                    if (index < currentStoryIndex) {
                        progressFill.style.width = '100%';
                    }
                    
                    progressBar.appendChild(progressFill);
                    progressContainer.appendChild(progressBar);
                });
            }

            function startStoryProgress() {
                clearTimeout(storyTimer);
                clearInterval(progressTimer);
                
                const progressFillElements = document.querySelectorAll('.story-progress-fill');
                if (progressFillElements.length <= currentStoryIndex) return;

                const progressFill = progressFillElements[currentStoryIndex];
                let progress = 0;
                const duration = 5000;
                const interval = 50;
                const increment = (interval / duration) * 100;
                
                progressTimer = setInterval(() => {
                    if (isPaused) return;
                    progress += increment;
                    progressFill.style.width = Math.min(progress, 100) + '%';
                    
                    if (progress >= 100) {
                        clearInterval(progressTimer);
                        nextStory();
                    }
                }, interval);
            }

            window.nextStory = function() {
                const user = storiesData[currentUserIndex];
                if (currentStoryIndex < user.stories.length - 1) {
                    currentStoryIndex++;
                    showStory();
                } else {
                    if (currentUserIndex < storiesData.length - 1) {
                        currentUserIndex++;
                        currentStoryIndex = 0;
                        showStory();
                    } else {
                        closeStory();
                    }
                }
            }

            window.previousStory = function() {
                if (currentStoryIndex > 0) {
                    currentStoryIndex--;
                    showStory();
                } else if (currentUserIndex > 0) {
                    currentUserIndex--;
                    const user = storiesData[currentUserIndex];
                    currentStoryIndex = user.stories ? user.stories.length - 1 : 0;
                    showStory();
                }
            }

            function handleKeyPress(event) {
                switch(event.key) {
                    case 'Escape': closeStory(); break;
                    case 'ArrowLeft': previousStory(); break;
                    case 'ArrowRight': case ' ': event.preventDefault(); nextStory(); break;
                }
            }

            document.getElementById('storyModal').addEventListener('click', function(e) {
                if (e.target === this) closeStory();
            });

            document.querySelector('.story-container').addEventListener('mousedown', function() {
                isPaused = true;
            });

            document.querySelector('.story-container').addEventListener('mouseup', function() {
                isPaused = false;
            });
            document.querySelector('.story-container').addEventListener('mouseleave', function() {
                isPaused = false;
            });
        });
    </script>

<<<<<<< HEAD
    <script src="modules/home/instagram.js"></script>

    <?php
    require_once __DIR__ . '/../../includes/footer.php';
    ?>
</body>
</html>
=======
<?php
    require_once __DIR__ . '/../../includes/footer.php';
?>
>>>>>>> 6373fe487644ce55e445e4adc7d05694d4ebb5fb
